### ISSUE TITLE
Decide on default rights, statements and APOs for books

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/google-books#1]
For example, <1924 books have public access, while books published after this date are citation only.  We can also consider setting an embargo period of (publication_year + 95 + 1) years in the future for any books that are set to citation only.

- [x] What is the logic for default object rights (and embargo) - assuming we know the publication year 
- [x] For materials for which we have determined access rights must be restricted (i.e. the work is in copyright), do we have to differentiate between Stanford and non-Stanford users
- [x] What is the logic for default object rights (and embargo) - assuming we do NOT know the publication year 
- [x] Do we have to take int account the region a user is in when trying to access a book (for the purposes of access and rights statement)? 
- [ ] what is the copyrights statement and usage and reproduction statement? (confirm what matches the APO)
- [ ] What is the copyright statement and usage and reproduction statement for each scenario
- [ ] Which APO(s) do we use?

**Comment by mjgiarlo** [comment]
@peetucket should you hang on to this ticket or punt it over to @andrewjbtw ?

**Comment by peetucket** [comment]
I can hang on to it and coordinate the work with Andrew.

**Comment by mjgiarlo** [comment]
@peetucket and @andrewjbtw: does this question relate to which APO(s) and/or collection(s) and/or tag(s) we assign to Google book content? Or is a separate question? We'll definitely need to button this up before we begin accessioning any content.

**Comment by andrewjbtw** [comment]
My understanding is that Google Books falls under the Stanford General Collections APO, but that needs to be confirmed. If all the books have the same APO, then we will need to use some other method to assign the rights, rather than the default rights set for that APO.

**Comment by peetucket** [comment]
- [ ] what is the logic for default object rights and embargo assuming we know the publication year
- [ ] what happens if we do not know the publication year?
- [ ] do we have to care about regions for the purposes of access and rights statement?
- [ ] what is the copyrights statement and usage and reproduction statement? (confirm what matches the APO)
- [ ] what is the visibility of copyrighted materials (e.g. stanford vs citation only for everyone)
- [ ] what is the APO(s)
- [ ] what is the collection

**Comment by peetucket** [comment]
approach 1:
* everything is citation only

approach 2:
* look at publication year, if less < 1890, public, else citation only, or place of imprint is USA and publication year < 1924 then public
* set embargo for future years
* no date, citation only

approach 3:
* also lookup visibility as determined by google and log if this is different than our computation

Note:  code archeology for Richard Anderson's code (project phoenix) that determined which books were out of copyright originally, cathy and lynn may know

**Comment by andrewjbtw** [comment]
@peetucket the subtickets to this ticket in the Project Phoenix JIRA https://jirasul.stanford.edu/jira/browse/PHNX-175 are the closest I've come so far to finding how copyright status was determined in the previous cycle.

**Comment by peetucket** [comment]
So something like just filtering GRIN's results by `viewability=VIEW_FULL`

**Comment by peetucket** [comment]
What Haiti Trust does: https://www.hathitrust.org/bib_rights_determination

Basically: US works published before 1925 are assigned a status of Public Domain in the US, and we follow the same 140/120 year rule that Google applies for non-US pubs

**Comment by jcoyne** [comment]
@peetucket I'm not familiar with the 140/120 year rule, can you explain that?  How will we determine if it is a US publication or not?

**Comment by mjgiarlo** [comment]
> @peetucket I'm not familiar with the 140/120 year rule, can you explain that? How will we determine if it is a US publication or not?

It looks like it's referred to in the link @peetucket shared, albeit in pseudocode form:

```
For non-US publications (PubPlace17 not “u”):
    If PubPlace is Canada or Australia
    then non_us_cutoff_year is current_year minus 120
    else non_us_cutoff_year is current_year minus 140
    If date_used is < non_us_cutoff_year
    then status = “pd”
    If date_used is >= non_us_cutoff_year and date_used < 1925 
    then status is pdus
    Otherwise, status = “ic”
```

**Comment by jcoyne** [comment]
@mjgiarlo where do the fields like PubPlace17 come from?

**Comment by mjgiarlo** [comment]
> @mjgiarlo where do the fields like PubPlace17 come from?

sounds like a @peetucket question :laughing:

**Comment by peetucket** [comment]
This information is hopefully in the METS xml file we are getting from google books, which saves us a catalog API lookup. Perhaps we can ask @andrewjbtw or @jgreben to look through a couple of these XML files from the sample books (here https://drive.google.com/drive/u/1/folders/1dslHFEs3nmQbqFOqmxt6NCxn6BpY5tdn) and help us figure out where we need to parse into the XML to get the publication date and the location.

**Comment by peetucket** [comment]
Note from an email chain where Tom asked metadata folks for their response to this approach laid out by Hathi...and there was general agreement that it seemed like a sensible approach, with Vitus calling out the following...not sure how this impacts us realistically

```

For serials, they would use VolDate if it exists. And VolDate is defined as “Latest year parsed from z30_description field.  Set to null if nothing could be parsed or if no z30_description.” Not sure what z30_description is, maybe something like the subfield Z of our call number fields (e.g. TP1 .K67|ZV.14 1997), in which case it would be a volume-by-volume determination, rather than a title level determination?
 
DateType eq 't':
  if Date2 exists, date_used = Date2
  if Date1 exists, date_used = Date1
  otherwise, date_used = unknown

Date type “t” is “publication date and copyright date”, with the publication date in Date1 and the copyright date in Date2. It is unclear to me what should happen according to this rule if both Date1 and Date2 exist, which is the majority of the case. Maybe the two “if” statements are hierarchical, i.e. the second “if” statement would kick in only when the record has no Date2? If that’s the case, then most records with date type = t would have date_used = Date2, i.e. copyright date.
 
In general, I don’t anticipate any major problem if we apply their algorithms against our records, other than the usual problems of errors and missing data, such as:
 
Federal documents not being identified by the government document code
U.S. publications that don’t have a “u” in PubPlace17 (last byte of the country of publication code in field 008, where a “u” indicates United States) and thus be classified as non-U.S. publication.
Records that have no date at all, or very imprecise dates like 1uuu, which they would turn into 1999 by replacing the “u” with a 9.
 ```

**Comment by peetucket** [comment]
Waiting on feedback from mimi about the text we can use for copyright/rights statements.

**Comment by peetucket** [comment]
As per decisions from Tom, we will use blank copyright and use and reproduction statements for now and may have to remediate later.
