### ISSUE TITLE
Algorithimically determine book rights based on catalog metadata

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/google-books#103]
@peetucket commented on [Thu Jan 09 2020](https://github.com/sul-dlss/sdr-api/issues/63)

Based on discussions about sul-dlss/google-books#1, we have come up with the following approach:

1. Using the symphony lookup service API (currently available in dor-services-app?), fetch marc XML for the given barcode/catkey.  ~~Alternatively - use the marcxml file in the google books download package.~~
1. Look at publication year in mac, if (PUB_YEAR < 1890) OR (PUB_YEAR < (CURRENT_YEAR - 96) AND IMPRINT_COUNTRY == USA), rights can be public.
1. If not OR if pub year is not available, rights are citation only and then set embargo as below
1. if IMPRINT_COUNTRY == USA and PUB_YEAR > (CURRENT_YEAR - 95), set embargo to release to public domain for PUB_YEAR - (CURRENT_YEAR - 96) + CURRENT_YEAR
1. if IMPRINT_COUNTRY != USA or unknown, set embargo to release to public domain for PUB_YEAR - (CURRENT_YEAR - 130) + CURRENT_YEAR
1. Then lookup visibility as determined by google (need API reference here) and log if this is different than our computation

**Comment by peetucket** [comment]
Based on discussions in stand-up on 1/10/2020, it is acceptable to parse the marcxml that is part of the google books download packages as an alternative to step 1 above (using our catalog service) - if this proves more reliable/performant.

**Comment by jcoyne** [comment]
Before we can start this we need to figure out where we find `IMPRINT_COUNTRY`.

**Comment by peetucket** [comment]
I believe this is basically the same question I asked @jgreben to look at in https://github.com/sul-dlss/google-books/issues/1#issuecomment-577301821  -- we need some help mapping fields out of the METS xml for pub country and pub year.

**Comment by justinlittman** [comment]
@peetucket What does "Then lookup visibility as determined by google (need API reference here) and log if this is different than our computation" mean?

**Comment by justinlittman** [comment]
@peetucket Is the algorithm described above logically identical with:
If USA and PUB_YEAR < CURRENT_YEAR - 95 then public.
Else if USA and PUB_YEAR is known, then embargo until PUB_YEAR + 95
Else if PUB_YEAR is known, then embargo until PUB_YEAR + 130
Else embargo until CURRENT_YEAR + 130

**Comment by peetucket** [comment]
> @peetucket What does "Then lookup visibility as determined by google (need API reference here) and log if this is different than our computation" mean?

I think the original request/idea from Tom or elsewhere was to compare our determination to Google's determination (if it was possible to see from the Google Books API that Searchworks uses to render links to google on their records page) and see if this was different, but I am now thinking this adds too much complication/slowness/another point of failure.

For the searchworks usage, you can see for example on https://searchworks.stanford.edu/view/4107534 on the left hand side under "More options", we've determined this book is available at Google Books, but only in limited preview mode.  And meanwhile we've determined this book is fully available: https://searchworks.stanford.edu/view/5620065

I presume the Searchworks team has done this with an API lookup to Google to see what Google's interpretation of copyright status is for that item.  So the original idea was to compare our computation with Google's.

**Comment by peetucket** [comment]
> @peetucket Is the algorithm described above logically identical with:
> 
> ```
> If USA
>    If PUB_YEAR < CURRENT_YEAR - 95 then public.
>    Else if PUB_YEAR is known, then embargo until PUB_YEAR + 95.
>    Else embargo until CURRENT_YEAR + 95
> Else 
>    If PUB_YEAR < CURRENT_YEAR - 130 then public.
>    If PUB_YEAR is known, them embargo until PUB_YEAR + 130
>    Else embargo until PUB_YEAR + 130.
> ```

That looks correct to me

**Comment by peetucket** [comment]
Where is the code that actually parses the MARCXML to extract the pub year and the location?  @vitustang requested to have a look at the parsing of the XML

**Comment by jcoyne** [comment]
@peetucket @vitustang https://github.com/sul-dlss/google-books/blob/master/app/models/marc_xml_record.rb

**Comment by ndushay** [comment]
Should this ticket be back on the Ready column, or marked blocked and put in the backlog column?  It doesn't seem to belong in review/QA

**Comment by jcoyne** [comment]
@ndushay what do you think it's blocked by or what further development do you think we need to do on this?

**Comment by ndushay** [comment]
I have no idea - it's just that it's hanging out in the "review/QA" column on the zenhub board;  if it's done, close it;  if it's not done, can it be moved to a more appropriate column?

**Comment by vitustang** [comment]
Peter,

I have reviewed the code that selects a year to use to determine whether a publication is still in copyright or in the public domain at:

https://github.com/sul-dlss/google-books/blob/master/app/models/marc_xml_record.rb

I want to say upfront that some of it was guesswork as I am not a programmer and not familiar with Ruby syntax. Having said that I want to bring four issues to your attention:


  1.  History of DateType = "t" (publication date and copyright date). If you look at the history section of the MARC 21 documentation<https://www.loc.gov/marc/bibliographic/bd008a.html> for the part of the 008 field that includes the DateType byte, you would see that this type of date situation was not always represented by the code "t", which was added in 1995. Prior to that, records for books used code "c".  Here are the relevant statements:

008/06 - Type of date/Publication status
c - Actual date and copyright date (BK, CF, MP, MU, VM) [OBSOLETE]
c - Serial item currently published [REDEFINED, 1995]
t - Publication date and copyright date [NEW, 1995]
Prior to its redefinition, code c had a different definition for books, computer files, maps, music, and visual materials than it did for serials. The difference was eliminated by the definition of a new code t (Publication date and copyright date) which is used in place of the obsolete nonserial code c. The definition of the serial code c was retained.

There are 11735 DIGI-SENT book format records that have DateType = c. We are only looking for a copyright date when DateType = t so we are missing these records. An example is ckey 4073821, which has this publication statement: 260    Boston :|bLittle, Brown,|c1927,c1897. DateType = c, Date1 = 1927, Date2 = 1897. Our pasrsing code is applying this rule when DateType = c:

#  if Date2 exists and Date2 > Date1, date_used = Date2
#  if Date1 exists, date_used = Date1

So, in this case it would select 1927, which makes it "in copyright", whereas if it had picked 1897, it would be in the public domain.


  1.  Date1 and Date2 appear to be "flipped" in their definitions:

@date1 ||= normalize_date(control_field_range('008', 11, 14))
@date2 ||= normalize_date(control_field_range('008', 7, 10))

In HathiTrust's Automated Bibliographic Rights Determination<https://www.hathitrust.org/bib_rights_determination> Date1 is 008:07-10 and Date2 is 008:11-14. The same is true in MARC 21<https://www.loc.gov/marc/bibliographic/bd008a.html>.



  1.  Date picked for serial publications. In HathiTrust's Automated Bibliographic Rights Determination<https://www.hathitrust.org/bib_rights_determination> they have a special rule for serials:

BibFmt eq 'SE' and VolDate exists:
date_used = VolDate

and VolDate is defined as " Latest year parsed from z30_description field.  Set to null if nothing could be parsed or if no z30_description." Don't know what their z30_description field is. The problem with serial publications is that their publication date is a range of years, and that range can cross the "public domain"/"in copyright" boundary. Here's an example. Ckey 2019108 has Date1 = 1880 and Date2 = 1957. DateType is "d". Our rule says if Date2 > Date1, picks Date 2. In this case the date picked would be 1957, which is in copyright. But we actually have volumes that are designated as 1893, 1895, 1899, 1911-1924. Are these volumes in the public domain?

Here is another example, the opposite of the one above. Ckey 348973 has Date1 = 1840, Date2 = 9999, DateType = c. According to our rules, 9999 = nil so the date picked would be 1840, which is in the public domain, but we have volumes that go all the way up to 1976. If we designate this entire serial as "public domain", would we be exposing some content that is still in copyright?


  1.  Number of title count. I think I have heard or read in various communication that we have 3.2 million titles scanned. I just want to clarify that that's not exactly true. According to our DIGI-SENT code in Symphony, we have sent 3.2 million *items* to Google for scanning. So, the unit of the 3.2 million scanned would appear to be item, not title. The 3.2 million items in Symphony that have the DIGI-SENT code are on 2,060,793 ckeys. Each ckey represents a "title". So, in terms of number of titles that have been scanned, it is more like 2 million than 3.2 million. And this directly relates to the problem with serials as described above. There are a lot of titles that have multiple items, and these items could be published over a period of time that spans the in copyright/public domain boundary. Picking one single date to determine the copyright status of all the items involved could be problematic. I'm not a copyright expert and can't offer an answer, but I thought it is an issue that is worth looking into.


-- Vitus

**Comment by justinlittman** [comment]
Thanks for the feedback @vitustang. I have created https://github.com/sul-dlss/google-books/issues/302 to make these changes.

**Comment by vitustang** [comment]
Thanks for the detailed analysis Vitus.  We will have a look at the issues you identified. For me, the most difficult is the date challenges with serials which span a period of time.  I presume Hathi Trust's approach is to be safe and mark all as copyrighted even if some earlier items are out of copyright.  This general approach makes sense to me if we have the metadata to support it (as you've laid out in bullet point 3).

From: Vitus Tang <vtang@stanford.edu>
Date: Monday, February 17, 2020 at 6:23 PM
To: sul-dlss/google-books <reply@reply.github.com>, Peter Alexander Mangiafico <pmangiafico@stanford.edu>
Cc: Darsi L Rueda <dlrueda@stanford.edu>, Nancy Lorimer <nlorimer@stanford.edu>
Subject: RE: [sul-dlss/google-books] Algorithimically determine book rights based on catalog metadata (#103)

Peter,

I have reviewed the code that selects a year to use to determine whether a publication is still in copyright or in the public domain at:

https://github.com/sul-dlss/google-books/blob/master/app/models/marc_xml_record.rb

I want to say upfront that some of it was guesswork as I am not a programmer and not familiar with Ruby syntax. Having said that I want to bring four issues to your attention:


1.       History of DateType = "t" (publication date and copyright date). If you look at the history section of the MARC 21 documentation<https://www.loc.gov/marc/bibliographic/bd008a.html> for the part of the 008 field that includes the DateType byte, you would see that this type of date situation was not always represented by the code "t", which was added in 1995. Prior to that, records for books used code "c".  Here are the relevant statements:

008/06 - Type of date/Publication status
c - Actual date and copyright date (BK, CF, MP, MU, VM) [OBSOLETE]
c - Serial item currently published [REDEFINED, 1995]
t - Publication date and copyright date [NEW, 1995]
Prior to its redefinition, code c had a different definition for books, computer files, maps, music, and visual materials than it did for serials. The difference was eliminated by the definition of a new code t (Publication date and copyright date) which is used in place of the obsolete nonserial code c. The definition of the serial code c was retained.

There are 11735 DIGI-SENT book format records that have DateType = c. We are only looking for a copyright date when DateType = t so we are missing these records. An example is ckey 4073821, which has this publication statement: 260    Boston :|bLittle, Brown,|c1927,c1897. DateType = c, Date1 = 1927, Date2 = 1897. Our pasrsing code is applying this rule when DateType = c:

#  if Date2 exists and Date2 > Date1, date_used = Date2
#  if Date1 exists, date_used = Date1

So, in this case it would select 1927, which makes it "in copyright", whereas if it had picked 1897, it would be in the public domain.


2.       Date1 and Date2 appear to be "flipped" in their definitions:

@date1 ||= normalize_date(control_field_range('008', 11, 14))
@date2 ||= normalize_date(control_field_range('008', 7, 10))

In HathiTrust's Automated Bibliographic Rights Determination<https://www.hathitrust.org/bib_rights_determination> Date1 is 008:07-10 and Date2 is 008:11-14. The same is true in MARC 21<https://www.loc.gov/marc/bibliographic/bd008a.html>.



3.       Date picked for serial publications. In HathiTrust's Automated Bibliographic Rights Determination<https://www.hathitrust.org/bib_rights_determination> they have a special rule for serials:

BibFmt eq 'SE' and VolDate exists:
date_used = VolDate

and VolDate is defined as " Latest year parsed from z30_description field.  Set to null if nothing could be parsed or if no z30_description." Don't know what their z30_description field is. The problem with serial publications is that their publication date is a range of years, and that range can cross the "public domain"/"in copyright" boundary. Here's an example. Ckey 2019108 has Date1 = 1880 and Date2 = 1957. DateType is "d". Our rule says if Date2 > Date1, picks Date 2. In this case the date picked would be 1957, which is in copyright. But we actually have volumes that are designated as 1893, 1895, 1899, 1911-1924. Are these volumes in the public domain?

Here is another example, the opposite of the one above. Ckey 348973 has Date1 = 1840, Date2 = 9999, DateType = c. According to our rules, 9999 = nil so the date picked would be 1840, which is in the public domain, but we have volumes that go all the way up to 1976. If we designate this entire serial as "public domain", would we be exposing some content that is still in copyright?


4.       Number of title count. I think I have heard or read in various communication that we have 3.2 million titles scanned. I just want to clarify that that's not exactly true. According to our DIGI-SENT code in Symphony, we have sent 3.2 million *items* to Google for scanning. So, the unit of the 3.2 million scanned would appear to be item, not title. The 3.2 million items in Symphony that have the DIGI-SENT code are on 2,060,793 ckeys. Each ckey represents a "title". So, in terms of number of titles that have been scanned, it is more like 2 million than 3.2 million. And this directly relates to the problem with serials as described above. There are a lot of titles that have multiple items, and these items could be published over a period of time that spans the in copyright/public domain boundary. Picking one single date to determine the copyright status of all the items involved could be problematic. I'm not a copyright expert and can't offer an answer, but I thought it is an issue that is worth looking into.


-- Vitus

**Comment by vitustang** [comment]
Peter,

Looking at what is said at HathiTrust's Automated Bibliographic Rights Determination<https://www.hathitrust.org/bib_rights_determination>:

BibFmt eq 'SE' and VolDate exists:
date_used = VolDate
VolDate is defined as "Latest year parsed from z30_description field.  Set to null if nothing could be parsed or if no z30_description."

I thought the same as you did, that they take the safe approach of marking all volumes as in copyright based on the lastest year found. But if you look at some serial records in their catalog, it appears that their parsing is actually more fine-grained than that. For example this record (https://catalog.hathitrust.org/Record/000497028) that crosses the 1925 boundary has the individual volumes listed like this:

[cid:image002.png@01D5E675.691873F0]

We could potentially take this more nuanced approach of taking the years from the individual volumes rather than from Date1 and Date2, or the more general approach of taking just the latest year found in the volumes. We do have the metadata for that (generally speaking), but it would require introducing two new things to the parsing code:


  1.  Paying attention to the format of the MARC record, and provide special treatment for those that are serial records.
  2.  Go down from the level of “title” to the level of “volumes within a title”

I suspect that what the HathiTrust refers to as the “z30_description field” might be similar to what we call the “analytic portion of the call number”. Serial call numbers are structured like this:

TP1 .K67|ZV.14 1997

The part before the |Z is the base call number, and the part that is in the subfield Z is the analytic portion. The analytic portion is basically a part designation, and for serials quite often there is a year in it. Using the example cited in #3 below, ckey 2019108, Symphony can output all the call numbers attached to the ckey:

977.6 .M66R 1955|
977.6 .M66R 1957|
977.6 .M66R 1895|
977.6 .M66R 1899|
977.6 .M66R 1911-1924|
977.6 .M66R 1893|

or just the analytic portion:

1955|
1957|
1895|
1899|
1911-1924|
1893|

and thus allow the use of volume level year for copyright determination purpose when it is available as described. If the call number does not have a year, then you could retract back to the title level and use Date1 and Date2.

Hope this information is useful for your challenging task of figuring out algorithmically what’s still under copyright and what’s not.

-- Vitus

**Comment by peetucket** [comment]
> 4.  Number of title count. I think I have heard or read in various communication that we have 3.2 million titles scanned. I just want to clarify that that's not exactly true. According to our DIGI-SENT code in Symphony, we have sent 3.2 million *items* to Google for scanning. So, the unit of the 3.2 million scanned would appear to be item, not title. The 3.2 million items in Symphony that have the DIGI-SENT code are on 2,060,793 ckeys. Each ckey represents a "title". So, in terms of number of titles that have been scanned, it is more like 2 million than 3.2 million. 

@vitustang so we are trying to get a sense of the scope of the challenges with serials before we decide how and if to address it ... based on this comment, are there any conclusions we can draw on the number of items that are likely to be serials and thus have potentials issues with multiple dates potentially crossing the copyright/non-copyright issue?

**Comment by vitustang** [comment]
@peetucket Of the 3.2 million items that have the DIGI-SENT code, 945,916 of them are items of a serial. They are linked to 112,202 ckeys. Since all serials have a beginning and an ending date, that's the number of cases that your copyright algorithm would have to deal with.
