### ISSUE TITLE
Estimate disk space needed for google books

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/google-books#11]
full size of 3.5 million books with all downloaded/preserved assets?

**Comment by aaron-collier** [comment]
Based on the 1118 example set books, the estimated size of the decompressed books for all 3283249 books (as reported by google), will be 272TB. This is captured in https://docs.google.com/document/d/1A7FiXk1GPnh6Psjcd1kq3EysUVklCDSXMmTAKGd-6uk/edit#

**Comment by peetucket** [comment]
From Julian: "...gBooks might involve upwards of 2.5 billion discrete files – that’s a challenge for pretty much any storage system, so as part of the gBooks assessment workcycle I’d like to see some analysis of file sizes; maybe a histogram of file sizes from a meaningful, representative sample of data. Given that I’ve heard 600TB as a potential corpus size, I’d imagine we’d need at least a couple of TB used for that analysis."

**Comment by peetucket** [comment]
From Aaron:

```
So far, I've downloaded 2338 books from gBooks for analysis. Note, this is quite a small subset compared to the 3.2 million, but it is randomized across that list, so it should be relatively accurate.

Decompressed packages for each book are:
1 image file per page (so far in either JP2, JPG, or PNG format)
1 html file per page (for the full text)
1 XML file with metadata
1 md5 checksum file

Across my set of example books I have found an average of 636 pages. So...


Based on 3283249 books: 
Total Files:
2,088,146,364 estimated pages
4,176,292,728 page files (1 html and 1 image)
3,283,249 XML files
3,283,249 MD5 files
4,182,859,226 total files
Estimated Size:
HTML average 78KB => 162TB Total
Images average 267KB => 557TB Total
XML average 347KB => 1.1TB total
MD5 average 40KB => 131GB total
720TB Total.
```

**Comment by justinlittman** [comment]
I suspect the HTML could be efficiently compressed.

**Comment by aaron-collier** [comment]
@justinlittman possibly, and I'm certainly not including that here as I think for pres/etc the MOAB and/or OCFL object will likely be compressed right? And outside of that, we may not want to store the html outside of the index/sdr object... 

Either way, I think that would be an implementation decision vs something out of the wc.

**Comment by aaron-collier** [comment]
Addition review of page data leads to a low end of approximately half of the original estimate, I think it's safe to provide a range, with the understanding that we do not have sufficient data to do a completely accurate estimate.

| Estimates | Low End | High End |
| ------------- | ------------- |
| Pages per item | 250  | 636  |
| Total pages | 820M  | 2B  |
| Page files | 1.6B | 4.1B |
| XML files | 3.2M | 3.2M |
| MDF files | 3.2M | 3.2M |
| Total files | 1.7B | 4.2B |
| Total space | 300TB | 720TB |
