### ISSUE TITLE
Add md5 checksums into contentMetadata from Google

### ISSUE THREAD

**Issue by justinlittman** [sul-dlss/google-books#110]
This is to ensure the checksums get verified in assembly WF in the checksum-compute step.   This robot will recompute checksums and confirm they match with the values you provided.

Note: Confirm that is how the robot works in assemblyWF

**Comment by mjgiarlo** [comment]
Question for @andrewjbtw and @peetucket. How important is this issue for the current work cycle given that we do not perform this step in e.g. pre-assembly?

**Comment by andrewjbtw** [comment]
What is active storage in this context? I'm not completely clear on the path that the files travel between retrieval from GRIN to the /dor workspace.

**Comment by justinlittman** [comment]
The checksum compute robot does compare existing checksums: https://github.com/sul-dlss/common-accessioning/blob/master/lib/robots/dor_repo/assembly/checksum_compute.rb#L36-L41

**Comment by justinlittman** [comment]
I don't think this is actually completed. I suspect that this is supported in sdr-api / client but not being passed from sdr_importer.
