### ISSUE TITLE
Determine how to authorize the GoogleBooks API on the server

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/google-books#124]
I've done this by manually copying my creds.json file to the server, which works, but is this the recommended way?

This decision should be documented.

- [ ] Check to see if we need to periodically refresh token if needed (asking Aaron at Hathi trust)

Manage clientIDs: https://console.developers.google.com/apis/credentials?authuser=1&project=su-gcp-sul-gbooks

We already have a clientID token for google-books-stage, just need to create one for -prod and move it to the server. I believe as long as one of the members of the infra team or others identified here (https://console.developers.google.com/iam-admin/iam?authuser=1&folder=&organizationId=&project=su-gcp-sul-gbooks) is an owner of the "SUL Google Books" project on the Google Developer Console, we will be able to manage new clientIDs without have a new google account.

**Comment by mjgiarlo** [comment]
@jcoyne Do you think we should shift this over to ready or leave it be for now?

**Comment by jcoyne** [comment]
I think we can leave it in new until our planning meeting

**Comment by aaron-collier** [comment]
Relevant doc: https://github.com/googleapis/google-api-ruby-client/blob/master/docs/oauth-installed.md

**Comment by peetucket** [comment]
Ideas:

- [ ] ask our contact at Hathi
- [ ] ask our contact at Google

**Comment by mjgiarlo** [comment]
We believe @justinlittman is working on a related issue now.

**Comment by jgreben** [comment]
Do we need a service account?
Will the creds we have time out?

**Comment by justinlittman** [comment]
I've taken a look at the Google docs again and still can't determine if the creds we have will time out.

**Comment by peetucket** [comment]
Email sent.

**Comment by peetucket** [comment]
They are collecting more info, meanwhile link to documentation they sent in our shared drive here: https://drive.google.com/open?id=11xo368cNSwuzgQZqaITywh1gL3Qh9gLF

A quick scan suggests it just instructions on how to create a key associated with an account, so perhaps not something we do not already know.

**Comment by peetucket** [comment]
Update from Google: "Also, for the API, a shared Google account should work -- if there are any other considerations, I'll let you know on that front, too."

So, we should create a shared Google gmail account for authorization -- and perhaps forward it to `dlss-infrastructure-team` so we will get any emails.

**Comment by peetucket** [comment]
Waiting on a response to how frequently we need to refresh our token

**Comment by peetucket** [comment]
From Aaron at Hathi:

```
The tokens do need to be refreshed periodically, but typically the OAuth library handles that for you. I haven't needed to re-authorize the application, if that's what your asking. I have run into an issue where sometimes requests fail periodically, but eventually they do succeed.. I suspect this might be an issue with multiple threads/processes using the same tokens but haven't tried to debug it.
```
