### ISSUE TITLE
Document in analysis plan what can go wrong and recommendations for a Project Manager to deal with it

### ISSUE THREAD

**Issue by justinlittman** [sul-dlss/google-books#13]
These include:
* Books that fail [conversion](https://books.google.com/libraries/Stanford/_failed).
* Books that get stuck in [in_process](https://books.google.com/libraries/Stanford/_in_process).
* Books that are [processed](https://books.google.com/libraries/Stanford/_converted), but not available for download (404).
* Books the are available for download but return a 404
* Books with corrupt download packages

**Comment by justinlittman** [comment]
Added to Analysis Report.

**Comment by ndushay** [comment]
who should this be assigned to?
