### ISSUE TITLE
Content metadata changes

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/google-books#132]
- object type should be "book" and resource type should be "page" for images (type "simple_book" if using `assembly-objectfile` gem: https://github.com/sul-dlss/assembly-objectfile/blob/master/lib/assembly-objectfile/content_metadata.rb#L30)
- publish/preserve/shelve should be true

**Comment by jcoyne** [comment]
We are using `simple_book` here: https://github.com/sul-dlss/sdr-api/blob/4278db56e6a4eb3de8dd488900a7dbcbc1a277ea/app/services/content_metadata_generator.rb#L32  so I'm not sure that is sufficient.

**Comment by andrewjbtw** [comment]
I think the issue with the pages being separate objects may be whatever corresponds to the "content metadata creation" option near the bottom of this preassembly instructions page: https://github.com/sul-dlss/pre-assembly/wiki/The-Application-Interface

It looks like it may have gone with "default" since that creates a resource for each object. The setting probably should be "filename". It's a little confusing because it seems like the grouping should be determined by calling it a book.

**Comment by peetucket** [comment]
HMM... it looks like the code is using bundle by `filename`: https://github.com/sul-dlss/sdr-api/blob/4278db56e6a4eb3de8dd488900a7dbcbc1a277ea/app/services/content_metadata_generator.rb#L31  which seems correct

**Comment by andrewjbtw** [comment]
Another difference with an example from prod: there's no druid prefix in the objectId in prod

prod: ```<contentMetadata objectId="cs204mj1611" type="book">```

stage: ```<contentMetadata objectId="druid:dr934br2164" type="book">```

**Comment by peetucket** [comment]
Did some debugging.  It looks like a lot of the problems are due to the fact the .jp2 files are being incorrectly identified as mimetype = "application/octet-stream" instead of "image/jp2" (also note that the .html are being identified as mimetype = "text/html" and not "application/xml").  This has the side-effect of the publish/preserve/shelve attributes defined here never being picked up and used: https://github.com/sul-dlss/sdr-api/blob/master/app/services/content_metadata_generator.rb#L46

It also has an impact on the resource types being set to "object" instead of "page", because for a simple_book, this resource level determination is based on if that resource has an images in it: https://github.com/sul-dlss/assembly-objectfile/blob/master/lib/assembly-objectfile/content_metadata/file_set.rb#L52-L53

If the code determines the resource has no images, you get "object" instead of "page".  Since the mime-types of the .jp2 files are coming in as `application/octet-stream`, it is deciding there are no images.

So this all comes down to mime-type determination code here: https://github.com/sul-dlss/assembly-objectfile/blob/master/lib/assembly-objectfile/object_fileable.rb#L119-L130

We've gone back and forth on how to make this mime-type code as general case as possible and have gone back and forth on it.  Basically it tries to use exif data first (blank in our case, I checked), then it uses the unix file system command, and if that fails, it uses a file extension look up (using the `mime-types` gem).  If we swapped the order of unix file system command with mime-type gem, we'd get the correct `image/jp2` mimetype, but it may have ripple effects elsewhere.  This is how we used to do it until August of 2019 when I swapped the ordering to support 3D objects that weren't getting the correct mimetypes set from the file extension (see https://github.com/sul-dlss/assembly-objectfile/pull/20).

SO.... maybe we need to extend the assembly-objectfile gem to allow us to specify our preferred mimetype generation method so we can control that ourselves?  Other ideas?

**Comment by peetucket** [comment]
> Another difference with an example from prod: there's no druid prefix in the objectId in prod
> 
> prod: `<contentMetadata objectId="cs204mj1611" type="book">`
> 
> stage: `<contentMetadata objectId="druid:dr934br2164" type="book">`

This one is easier, we just need to append the "druid:" namespace to the druid variable here: https://github.com/sul-dlss/sdr-api/blob/master/app/services/content_metadata_generator.rb#L26

**Comment by peetucket** [comment]
Possible update to `assembly-objectfile` gem to allow us better control over mimetype generation: https://github.com/sul-dlss/assembly-objectfile/pull/38

**Comment by andrewjbtw** [comment]
Where are you seeing the jp2 files identified as ```application/octet-stream```? In the contentMetadata they're listed as ```image/jp2```.

**Comment by peetucket** [comment]
I was test things manually using the assembly-objectfile gem on the sdr-api machine where the code is being executed and that's what it was returning for mime-types, which are used to generate the publish/preserve/shelve attributes and grouping.  But the mimetypes were not actually added to contentMetadata at that step, they were added later by an assembly robot.  But that is odd they are different - and worth more investigation.

**Comment by andrewjbtw** [comment]
For file type identification in general, it might be worth looking at at tool like Siegfried [https://www.itforarchivists.com/siegfried/](https://www.itforarchivists.com/siegfried/) uses the UK National Archives PRONOM file format registry, among other sources. It would require more work to implement, but I think it's likely to be more precise. But distinguishing file-types for plaintext like xhtml vs. html is notoriously difficult.

**Comment by peetucket** [comment]
talk to the hand if you have more comments

(i.e. future changes to contentMetadata should be captured in other tickets)

**Comment by jcoyne** [comment]
superseeded by #132
