### ISSUE TITLE
Create Google Books fixture objects

### ISSUE THREAD

**Issue by mjgiarlo** [sul-dlss/google-books#138]
Create a range of fixture objects based on real Google Books data. The fixture objects should vary in terms of both size—"large" books vs. "small" books—and state: available, in-process, converted, failed conversion (w/ different failure reasons), previously downloaded, checked in, new.

**Comment by jcoyne** [comment]
Can we discuss this in planning next week before moving forward on this? I’d like to understand the why and I have some concerns about where these belong (not in public git)

**Comment by mjgiarlo** [comment]
@aaron-collier should this issue be in review/QA?

**Comment by aaron-collier** [comment]
I think this should be closed. I added some fixture data that seems sufficient and that was merged a bit ago. I'm going to close this, if anyone wants it re-opened or a new ticket, happy to follow up.

**Comment by mjgiarlo** [comment]
@aaron-collier thanks!
