### ISSUE TITLE
Create book model status flow diagram 

### ISSUE THREAD

**Issue by mjgiarlo** [sul-dlss/google-books#139]
And map/correlate with rake tasks. This will help the team understand the flow between the statuses.

**Comment by ndushay** [comment]
See also #24

**Comment by jcoyne** [comment]
Seems like a duplicate of 24 to me

**Comment by mjgiarlo** [comment]
@jcoyne Perhaps this is a slight expansion of scope for #24.

**Comment by mjgiarlo** [comment]
I believe the following documentation and diagram mean this issue is now closed:

* https://docs.google.com/drawings/d/1VWLk9jvBkf2FEbwG50Z9YW1wqhuTgbW4K_txThfPkgc/edit
* https://github.com/sul-dlss/google-books#usage-1
* https://github.com/sul-dlss/google-books#flow
