### ISSUE TITLE
Analyze catalog records to get a count of google books that will be coming out of copyright soon

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/google-books#152]
Tom has requested an analysis that gives us rough counts of the Google Books in our catalog that would be publicly visible now, and then in 2021, 2022, 2023, and 2024.  This could be done as a first pass by looking at the publication year and counting books with publication years:

(public now) = pub year < 1925
(public in 2021) = pub year == 1926
(public in 2022) =  pub year == 1927
(public in 2023) =  pub year == 1928
(public in 2024) =  pub year == 1929

This doesn't take in account US vs non US works, but could be a rough guide

**Comment by jcoyne** [comment]
@peetucket How are we going to identify which books should be in this population? How will we get the pub_year?

**Comment by peetucket** [comment]
It should be in the catalog record (same spot we will need to use do the rights computation) -- I chatted with Josh earlier who is able to pick it up, and we will need his expertise when doing the rights computation as well.

**Comment by jgreben** [comment]
@peetucket are we interested in counts for items or titles? The counts will come out different depending on which we use.

There is a file of catalog keys on the production Symphony server generated on 4/2009 with almost 5M keys. If these are the correct catalogs records to use I can use this file to do the analysis. I can also ask @dlrueda what knowledge she has about these files.

```
4953958 temp2_uniq
```

For a count of items, If there is a more recent set of barcodes to use that you know about, let me know and I can use that instead, or there is also a set of files on Symphony with 13M call numbers (and I assume the 5M catalog keys mentioned above are the subset of catalog records for those items):

```
151009 selcallnum_A
   453016 selcallnum_B
    66188 selcallnum_C
   997341 selcallnum_D
  1150458 selcallnum_dewey
    79479 selcallnum_E
   160121 selcallnum_F
   419976 selcallnum_G
  1083884 selcallnum_H
     7101 selcallnum_I
   268971 selcallnum_J
   446948 selcallnum_K
   164359 selcallnum_L
   231921 selcallnum_M
   319444 selcallnum_N
     1923 selcallnum_O
  4470820 selcallnum_other
  1426689 selcallnum_P
   435052 selcallnum_Q
   112351 selcallnum_R
    38884 selcallnum_S
   259227 selcallnum_T
    50927 selcallnum_U
    12068 selcallnum_V
     1626 selcallnum_W
   197851 selcallnum_Z
 13007634 total
```

**Comment by peetucket** [comment]
Forgot to lookup where the barcodes from Google are...they are in this shared google drive: https://drive.google.com/drive/u/1/folders/1aTmsERAd-gqcj_hMFtuexVS1zGC3d98M in a file called "all_grin_barcodes.txt"

sorry for my ignorance, but can you clarify the difference between "item" and "title" -- is it that a single book title may have multiple volumes and thus multiple barcodes?

**Comment by peetucket** [comment]
It is also hopefully in the METS xml file we are getting from google books, which saves us a catalog API lookup.  Perhaps we can ask @andrewjbtw or @jgreben to look through a couple of these XML files from the sample books (here https://drive.google.com/drive/u/1/folders/1dslHFEs3nmQbqFOqmxt6NCxn6BpY5tdn) and help us figure out where we need to parse into the XML to get the publication date and the location.

**Comment by jgreben** [comment]
A title corresponds to a catalog record, but a catalog record may have more than one item with different call numbers for multiple copies or volumes. So for example "The World as Will and Representation" by Arthur Schopenhauer has two volumes under the same title that share the same catalog record. E.g. https://searchworks.stanford.edu/view/1999790 would get counted once for "public in 2021" if we ran it by title, or counted twice if we ran it by item.

If I use the file of barcodes you provided in that link, we would be looking at items because usually each item has a single barcode.

**Comment by peetucket** [comment]
Thanks.  I think the spirit of the request is better fulfilled by title (basically unique books), but on the other hand, I don't think its worth doing a lot of extra work to do it that way to fulfill the request for numbers (I imagine that number of books that have multiple copies or volumes is not a huge percentage)?

**Comment by jgreben** [comment]
This is the pub date algorithm:
```
1) 008/11-14 if 008/06 is "t"
2) 260 $c if the date is preceded by "c" or "©", or 264 $c with 2nd indicator set to "4"

For publication date:
1) 008/07-10 if 008/06 is "s"
2) 008/11-14 if 008/06 is "r" (gets the original date of a reprinted edition; 008/07-10 has the reprint publication date)
3) 260 $c, or 264 $c with 2nd indicator set to "1"
```

**Comment by jgreben** [comment]
Looking at the data, I don't think that 👆 algorithm is quite right. I think it should be:

008/11-14 if "r" or "t"
008/07-10 if any other value in position 06

**Comment by jgreben** [comment]
See https://github.com/sul-dlss-labs/google_books_pub_dates

**Comment by peetucket** [comment]
Thanks, so just to be clear, this shows there are ~80,860 books out of the 3 million that are potentially out of copyright, with a couple thousand more coming out each year.

**Comment by jgreben** [comment]
> Thanks, so just to be clear, this shows there are ~80,860 books out of the 3 million that are potentially out of copyright, with a couple thousand more coming out each year.

Yes, and there were about 12K books that did not have a parsable date in the 008 field that my report could easily capture. If we used the more robust algorithm it would have changed the numbers but only slightly.

Also, the number of pages is definitely an **_underestimate_** of the number of pages that can be expected, as it only counted the parsable fields with appropriate data, and should only be considered as a starting point. If needed I could similarly count the number of items that were not counted for number pages.

**Comment by jgreben** [comment]
I went ahead and added the count of pages not parsed because it was easy:
```
Dates not parsed	11893
Pages not parsed	313182
```
 So the number of pages is about 10% too low, all else being roughly equal...

**Comment by andrewjbtw** [comment]
> Thanks, so just to be clear, this shows there are ~80,860 books out of the 3 million that are potentially out of copyright, with a couple thousand more coming out each year.

This is quite a bit lower than the previous project's ~180,000 books downloaded. The old method of determining rights must have been much less conservative.

**Comment by jgreben** [comment]
> > Thanks, so just to be clear, this shows there are ~80,860 books out of the 3 million that are potentially out of copyright, with a couple thousand more coming out each year.
> 
> This is quite a bit lower than the previous project's ~180,000 books downloaded. The old method of determining rights must have been much less conservative.

Do you know what the old method was and can share? I will review the process I used and make sure that nothing was being skipped or dropped that should have been counted.

**Comment by jgreben** [comment]
@peetucket @andrewjbtw Looks like my catalogdump was too small. I am rerunning the dump in case it got interrupted the last time and also checking to make sure that the majority of the dumped records actually have a 008 and 300 field.

**Comment by jgreben** [comment]
Looks like the catalogdump produced a file that did not include everything. I re-ran it and it got more (this time 987541 records). I am trying to determine why it keeps coming up short.

**Comment by peetucket** [comment]
Doh. Ok, I reported those initial numbers out, but can revise upward if needed.

**Comment by andrewjbtw** [comment]
I think the previous method used the viewability designation returned by GRIN. They may have done some more processing after that, but the most information I've found so far is in this collection of tickets from the previous project JIRA: https://jirasul.stanford.edu/jira/browse/PHNX-175 

This ticket looks like the one with the most detail: https://jirasul.stanford.edu/jira/browse/PHNX-183

**Comment by jgreben** [comment]
Here is the report ran with all of the marc records associated with all of the barcodes:
https://github.com/sul-dlss-labs/google_books_pub_dates/tree/master/report

**Comment by jgreben** [comment]
@peetucket @andrewjbtw can this be closed now?
