### ISSUE TITLE
See if we can determine publication country from the METS file

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/google-books#157]
This can then be used to determine what access controls should be applied.

**Comment by justinlittman** [comment]
Admittedly, my MARC foo is a bit rusty, but I would expect to find this in the 008/15-17 (https://www.loc.gov/marc/bibliographic/bd008a.html).

However, in my evaluations of the MARC records embedded in the METS for a sample Google Books:
* 6 had no 008.
* 1 had an 008, but 15-17 was blank.
* 1 had ilu (Illinois) for 008/15-17.

So I think the answer is "no".

**Comment by jcoyne** [comment]
@peetucket @andrewjbtw FYI ☝️ ☝️☝️☝️

**Comment by ndushay** [comment]
ask Arcadia if the country is anywhere in a 264 or 260 (or any other place) in Marc.  I think it might be 260b and 264b

**Comment by peetucket** [comment]
Yes, perhaps we can ask @jgreben to help us here (either directly, or coordinate with Metadata)

**Comment by justinlittman** [comment]
None of the records in my sample have 264.

260 has the place of publication, but it is very uncontrolled:
```
downloads/20500020403/STANFORD_20500020403.xml:<datafield tag="260" ind1=" " ind2=" ">
downloads/20500020403/STANFORD_20500020403.xml-<subfield code="a">[Singapore]</subfield>
--
downloads/20500021140/STANFORD_20500021140.xml:<datafield tag="260" ind1=" " ind2=" ">
downloads/20500021140/STANFORD_20500021140.xml-<subfield code="a">Princeton, N. J.,</subfield>
--
downloads/20500021247/STANFORD_20500021247.xml:    <datafield tag="260" ind1=" " ind2=" ">
downloads/20500021247/STANFORD_20500021247.xml-      <subfield code="a">New York :</subfield>
--
downloads/20500020429/STANFORD_20500020429.xml:<datafield tag="260" ind1=" " ind2=" ">
downloads/20500020429/STANFORD_20500020429.xml-<subfield code="a">Englewood Cliffs, N.J.,</subfield>
--
downloads/20500020411/STANFORD_20500020411.xml:<datafield tag="260" ind1=" " ind2=" ">
downloads/20500020411/STANFORD_20500020411.xml-<subfield code="a">London,</subfield>
--
downloads/20500020615/STANFORD_20500020615.xml:<datafield tag="260" ind1=" " ind2=" ">
downloads/20500020615/STANFORD_20500020615.xml-<subfield code="a">New York,</subfield>
--
downloads/20500021394/STANFORD_20500021394.xml:<datafield tag="260" ind1=" " ind2=" ">
downloads/20500021394/STANFORD_20500021394.xml-<subfield code="a">Scranton,</subfield>
--
downloads/20500021174/STANFORD_20500021174.xml:    <datafield tag="260" ind1=" " ind2=" ">
downloads/20500021174/STANFORD_20500021174.xml-      <subfield code="a">Chicago :</subfield>
--
downloads/20500020097/STANFORD_20500020097.xml:<datafield tag="260" ind1=" " ind2=" ">
downloads/20500020097/STANFORD_20500020097.xml-<subfield code="a">Boston,</subfield>
--
downloads/20500018600/STANFORD_20500018600.xml:<datafield tag="260" ind1=" " ind2=" ">
downloads/20500018600/STANFORD_20500018600.xml-<subfield code="a">New York,</subfield>
```

I checked with Arcadia. We're looking in all the right places.

**Comment by peetucket** [comment]
I guess the next question is, do we have this in our own catalog record for the same barcode (i.e. is the data just absent completely which we can't do anything about) or is missing from google only (in which case we would need to do lookups against our own catalog instead)?

**Comment by justinlittman** [comment]
Great question @peetucket. I looked up 3 in the catalog and all had useful 008s.

```
008 720229s1964 paua b 000 0 eng
008 930330s1949 nyu 000 0 eng 
008 930330t19701969ilua b 001 0 eng
```

**Comment by jcoyne** [comment]
Seems like we have an answer here.  We can't get it from the METS, but we can get it from the catalog record.
