### ISSUE TITLE
Compare GRIN provided list of barcodes with symphony provided list of barcodes

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/google-books#16]
The goal is to determine if the books GRIN is aware of as belong to Stanford are the same as the books we have sent to Google to digitization.  This will tell us if there are books that we sent to Google that had already been digitized from other providers and thus were not digitized again under Stanford's "account".  If this is true, we would need to figure out how to get those books.

- [x] fetch a complete list of barcodes from GRIN
- [x] fetch a complete list of barcodes from symphony (or the stanford system that has such a list) - @dlrueda can provide
- [x] compare the lists and find the diffs

**Comment by aaron-collier** [comment]
Will write this up in our docs, but:

Exported from Symphony: 3214447 
At Google: 3209004
Missing from google: 5443
Available for conversion: 2577190
Not Available: 631814
Unknown: 74245
