### ISSUE TITLE
Confirm if it is possible to redownload books that have been downloaded from Google

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/google-books#163]
Many years ago we asked Google to process a large number of books (~180k) and then we downloaded them.  We believe that if we were to now request these books to be re-proccessed so they could be downloaded again, we get an error back from Google (or if it is otherwise not possible).  

We need to confirm if this is true and if so, send a message to Google to figure out how to proceed/reset.

- [x] verify the status of previously downloaded books
- [x] try to request a previously downloaded book

**Comment by peetucket** [comment]
Some barcodes from this initial set to use as a test:

36105048187814
36105014928126
36105049302784

Need more?  Facet in Argo for the initial Google Books accessioning project X years ago: https://argo.stanford.edu/catalog?f%5Bexploded_tag_ssim%5D%5B%5D=Google+Book

**Comment by justinlittman** [comment]
It is not possible. Processing was requested on the following books, but we are unable to download:
![image.png](https://images.zenhubusercontent.com/5d8270f64def500001d12f23/737b60ec-7661-414f-9a8b-f1f029f7c942)

**Comment by peetucket** [comment]
I just noticed that all of those barcodes start with 205, which are the same ones that we don't have catkeys for, and that Darsi says are likely because they are outside of SUL (ie. Lane Medical or some other catalog).  I wonder if this is a coincidence or if there something going on here.

But to be clear, is this the right question for Google?

```
It appears that if we've previously requested processing and downloaded a book (e.g. many years ago during a previous effort), we can't re-download the book again.  For example, here are some barcodes that had been previous requested and downloaded but we aren't able to anymore.  Note that we are able to request processing of the book which returns successfully, but when try to download it, we get a 404.

20500020615
20500020429
20500020411
20500020403
20500020097

```

**Comment by andrewjbtw** [comment]
When I first got access to GRIN and was just seeing how the web interface looked, I requested conversion for a previously downloaded book with barcode 36105002111545. I'd almost given up because it took a few days before it was converted, but it looks like it's downloadable now. You can see that it has a previously downloaded date of 2012/04/25.

I'm not set up for decrypting, so I haven't actually tried to download it myself.

**Comment by peetucket** [comment]
HMM... I'm wondering if there is something going on with those 205xxx barcodes.  They don't exist in our catalog and they can't be re-downloaded.  I wonder if they were pulled from Lane or GSB?  It's still worth me asking Google.  Still waiting to see what else I may need to ask them in the email.

**Comment by justinlittman** [comment]
The phrasing of your question looks good to me @peetucket

**Comment by peetucket** [comment]
Ok, the response is:

```
it looks like for any books that have previously been downloaded (and not reprocessed & re-analyzed on our side since the last download), the book is unable to be (re)downloaded. This is done by design.  If you have a collection of barcodes that need to be reprocessed for re-downloading, then we could certainly help with that -- but it might take some time, upwards of a month or two.  
```

So the question is...would we know ahead of time what these barcodes would be?  I guess we could query for all of the books that we accessioned the first time and assume it would be at least all of those.  Or just throw into the exception queue and go back later to ask them to be reset?  Other ideas?

**Comment by peetucket** [comment]
Update from Google:  "it sounds like there might be something else at work with the GRIN issue you're seeing (other folks have confirmed that reprocessing might not be needed for re-downloading), so we'll need to investigate with the Book engineers.  I hope to have more info for you soon "

**Comment by mjgiarlo** [comment]
We confirmed that we can re-download books that have already been downloaded from Google. If the book is still in the CONVERTED state, we can re-download immediately. If it is in PREVIOUSLY_DOWNLOADED, it must be processed first, and then it will be become ready for download.
