### ISSUE TITLE
Specify preferred barcode ordering for download from Google

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/google-books#164]
We will need to specify a preferred ordering of processing of barcodes (i.e. the order in which we request processing and download from Google).  This will allow us to accession books in an order of maximal stakeholder value.  Work will need to be done separately to determine what the order should be (e.g. public domain first, certain call number ranges first), but the google books app should have the ability to use a lookup by barcode to determine a priority sort ordering.

**Comment by jcoyne** [comment]
@peetucket I'm not sure I understand what this means:

> google books app should have the ability to use a lookup by barcode to determine a priority sort ordering.

Looking up

**Comment by peetucket** [comment]
Sorry, what I'm trying to say (and perhaps drifter into implementation) is that we've had a request to allow us to specify an ordering of barcodes in some fashion to prioritize when downloading books.  The idea being that if it takes year(s) to download all of the books, we may want to allow stakeholders to tell us which ones they care about more and do those first.  We could also do the ones out of copyright first for example.

So we need a way of indicating an ordering of barcodes, and a way to get that ordered list of barcodes into the system and maintain it (presumably into a database table?)

There would be a separate (non-development) work that would involve translating the stakeholder requests into a list of barcodes (presumably by using our catalog data and some querying by library systems folks).

**Comment by justinlittman** [comment]
For what it is worth, I'd argue this is the sort of hypothetical requirement that should not be implemented until an actual stakeholder shows up to describe the specific requirements. Otherwise, the solution that we implement is unlikely to be correct.

**Comment by andrewjbtw** [comment]
I think we can split off the technical requirement of providing a list of barcodes to download from whatever procedure is eventually followed to arrive at that list of barcodes.

Getting to a list of barcodes matching a set of requirements (like subject or time period) should be a mediated service that's likely to involve the stakeholder using catalog data to identify books of interest. I don't think it's something that people should be able to do except by request, given the scale of this project. I also don't think that part of the process should be in scope for this work cycle or possibly even for infrastructure at all.

So I suggest making this ticket specific to taking a list of barcodes and downloading the items matching those barcodes.

**Comment by andrewjbtw** [comment]
I also don't think it should be necessary to do other operations like sorting the list, either - if the stakeholder needs a specific order, they should supply it when making the list. Given the uncertainty over the speed of conversion, I don't think we can even guarantee an order with any precision.

**Comment by justinlittman** [comment]
So one suggested approach to satisfy this requirement is to add a priority field (integer) to the book record. Books with the highest priority will be processed first.

There will also a mechanism (say, a rake task) for loading a CSV of barcodes and priorities. (Books records matching the barcodes will have their priorities updated.) Creating this CSV file will be handled outside the application.

**Comment by peetucket** [comment]
That sounds like a reasonable implementation and allows for us to update priorities over time (i.e. we get a list of barcodes one week and then a month later an updated list.  Using numbers, we'd be able to tweak priorities.
