### ISSUE TITLE
Shelve google provided METS-like xml file, but not the MD5 file.

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/google-books#169]

**Comment by mjgiarlo** [comment]
@jcoyne should this be blocked by shelving/stacks-related discussions? backlog it?

**Comment by jcoyne** [comment]
Yes.

**Comment by andrewjbtw** [comment]
The METS xml file should follow the same rules as the JP2s and HTML files

**Comment by andrewjbtw** [comment]
The MD5 file should be preserved regardless
