### ISSUE TITLE
Upgrade gpg / libcrypt on GB server

### ISSUE THREAD

**Issue by justinlittman** [sul-dlss/google-books#181]
Decrypting Google books are working differently on the server than locally, viz., the mechanism for bypassing the manual passphrase entry screen is not working.

Best guess is that this is because the versions of gpg and libcrypt on the server are vastly out of date.

Locally for me:
* gpg: 2.2.15
* libcrypt: 1.8.4

GB server:
* gpg: 2.0.22
* libcrypt: 1.5.3

Please upgrade these libraries to the latest available.

**Comment by rsmith11** [comment]
2.0.22 and 1.5.3 are the latest packages for Centos7.  I'll need to investigate if there are other repositories that offer them.

**Comment by rsmith11** [comment]
I believe I've found a solution.  I've found gnupg and libcrypt packages and they install in a secondary directory, as to not interfere with system gpg files.  They are installed under /opt/atomicorp/atomic.  I've updated the gb user's .bash_profile to look for those paths first, so that now when logged in as the gb user you get:

```
[gb@google-books-stage ~]$ gpg --version
gpg (GnuPG) 2.2.12
libgcrypt 1.8.4
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Home: /opt/app/gb/.gnupg
Supported algorithms:
Pubkey: RSA, ELG, DSA, ECDH, ECDSA, EDDSA
Cipher: IDEA, 3DES, CAST5, BLOWFISH, AES, AES192, AES256, TWOFISH,
        CAMELLIA128, CAMELLIA192, CAMELLIA256
Hash: SHA1, RIPEMD160, SHA256, SHA384, SHA512, SHA224
Compression: Uncompressed, ZIP, ZLIB, BZIP2
```
If this works for you, then I'll push the same changes to google-books-prod.

**Comment by jcoyne** [comment]
@rsmith11 why aren't we on Centos8?

**Comment by rsmith11** [comment]
UIT has not created/released PAM krb5, wallet, kstart, remctl, and some other packages that are needed for Centos8.  We've asked for them, but are holding on until those packages are available to us.

**Comment by justinlittman** [comment]
Thanks @rsmith11. We're able to proceed with this solution.

**Comment by rsmith11** [comment]
Thanks.  I'll make the same changes on production soon.

**Comment by rsmith11** [comment]
Changes are in production now.
