### ISSUE TITLE
Compute approximate time cost for Stanford processing prior to accessioning

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/google-books#20]
Once we download a book from Google, some steps will be necessary to prep the objects for accessioning.  The most time consuming prep step is likely to be the unzipping process.  We should estimate the time cost so we can better estimate total time.

- [x] Download a sample number of google books (e.g. n = 100)
- [x] Unzip all and get average time

**Comment by aaron-collier** [comment]
- Downloaded 1000 books. => 105 minutes (1.75 hours)

**Comment by peetucket** [comment]
Was that download time only or also unzip (or is the unzip so fast it doesn't matter)?

**Comment by aaron-collier** [comment]
Capturing analysis here: https://docs.google.com/document/d/1A7FiXk1GPnh6Psjcd1kq3EysUVklCDSXMmTAKGd-6uk/edit
