### ISSUE TITLE
Run analysis of content in the books we have sent to Google for scanning

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/google-books#21]
It would helpful to understand the types/categories of content available when determining the use cases and constituents that can be served with the accessioned google books.  For example:

- [x] what percentage are public domain (< 1924)
- [x] percent in different subject areas

Can we do this by exporting list of books from our system with the MARC data and analyzing this?  Look for a "digisent" field in MARC to indicate which books we've sent?

**Comment by aaron-collier** [comment]
Approximately 600,000 barcodes are public domain ( < 1924)

**Comment by aaron-collier** [comment]
| Call No. Range | LOC Subject | Count |
| --- | --- | --- |
| A | GENERAL WORKS | 68158, 
| B | PHILOSOPHY | 153199 | 
| C | AUXILIARY SCIENCES | 49613 | 
| D | WORLD HISTORY | 381502 | 
| E | HISTORY OF THE AMERICAS | 25234 | 
| F | HISTORY OF THE AMERICAS | 59230 | 
| G | GEOGRAPHY | 48885 | 
| H | SOCIAL SCIENCES | 452531 | 
| J | POLITICAL SCIENCE | 93751 | 
| K | LAW | 242324 | 
| L | EDUCATION | 58107 | 
| M | MUSIC | 86373 | 
| N | FINE ARTS | 104575 | 
| P | LANGUAGE AND LITERATURE | 499206 | 
| Q | SCIENCE | 101190 | 
| R | MEDICINE | 17007 | 
| S | AGRICULTURE | 26523 | 
| T | TECHNOLOGY | 88827 | 
| U | MILITARY SCIENCE | 15529 | 
| V | NAVAL SCIENCE | 4178 | 
| Z | BIBLIOGRAPHY | 77783 | 

These are codes that don't match https://www.loc.gov/catdir/cpso/lcco/ and I'll spot check what these actually are.

NON-LC CALL NUMBERs
| Code | Count |
| --- | --- |
| 1 | 7295 | 
| 2 | 8142 | 
| 3 | 115146 | 
| 4 | 4626 | 
| 5 | 90106 | 
| 6 | 41804 | 
| 7 | 1881 | 
| 8 | 77401 | 
| 9 | 39945 | 
| 0 | 46482 | 
| O | 30 | 
| W | 3999 | 
| Y | 116318 | 
| I | 5794 | 
| X | 1772 | 
| " " | 18 |
