### ISSUE TITLE
Create/Pick Collection and APO for Google Books and update configuration

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/google-books#236]

**Comment by andrewjbtw** [comment]
Options:

## Option 1: Use the library General Collections APO

Benefits
- the vast majority of the books are from the general collection
- treats books as much as possible as "normal" repository objects

Risks
- some books may not be in the general collections (special collections, affiliate libraries)
- the General Collections APO default object rights are "world","world" and we would need to be careful not to apply them

## Option 2: Use a specific Google Books APO

Benefits
- Keeps project together under one policy
- Can tailor default object rights to this special case
- Doesn't depend on correspondence with how the library collections are organized

Risks
- It treats Google Book objects as special cases
- It prevents combining Google Book objects and non-Google book objects in a collection (I think)

**Comment by andrewjbtw** [comment]
At the beginning of this project, I was leaning towards option 1, but the more I think about it, I'm leaning towards the Google Books specific APO, largely on the basis that the books included in the project likely span more than one type of library collection.

I don't think collections can span more than one APO, so we need to settle the APO before settling the collection.

FWIW, there already is a Google Books specific APO and collection from last year's analysis cycle:

APO: https://argo.stanford.edu/view/druid:gd935rx2507
Collection: https://argo.stanford.edu/view/druid:vk199pb0657

**Comment by jgreben** [comment]
Waiting for APO in Prod.

**Comment by andrewjbtw** [comment]
Ok, we now have an APO and Collection for Google Books. We decided to give this project its own, new, set of druids because the SDR objects should be attached to specific documents for the Google Books project. It does not make sense to associate it with any of the generic library collections agreements because these books span both general and special collections.

APO: bf569gy6501
Collection: yh583fk3400

**Comment by andrewjbtw** [comment]
I made a separate ticket for updating the configuration with these druids: https://github.com/sul-dlss/google-books/issues/452
