### ISSUE TITLE
Create architecture / workflow diagram

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/google-books#24]
Create a diagram showing the various components and SDR workflows we expect google content to flow through

**Comment by mjgiarlo** [comment]
# Architecture diagram

![Google Books-to-SDR Architecture](https://user-images.githubusercontent.com/131982/73568787-f433d780-441d-11ea-8e6a-39d03980d9b0.png)

**Comment by mjgiarlo** [comment]
I suspect we can close this issue now, with the work done above. I recommend we update https://docs.google.com/drawings/d/1NKjYGTISJIdNJA5b9ONWM_pJMwBICGWiq5XnEgHArBo/edit as we go and put in issues to amend/correct it in specific ways.
