### ISSUE TITLE
Move "Books By Status" from /stats to /statuses

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/google-books#245]
We need the counts that currently show up here:
<img width="1152" alt="Screen Shot 2020-02-05 at 8 49 43 AM" src="https://user-images.githubusercontent.com/92044/73852292-8b20db00-47f4-11ea-98d9-47601a2037b2.png">

To be in the nav pills here:

<img width="1168" alt="Screen Shot 2020-02-05 at 8 50 37 AM" src="https://user-images.githubusercontent.com/92044/73852439-c6bba500-47f4-11ea-8bf5-8cf474fc040c.png">

Once that is  done, the "Books By Status" section can be removed from the `/stats` page.

**Comment by justinlittman** [comment]
And also use the same labels as statuses. "Deposit failed", not "DEPOSIT_FAILED".
