### ISSUE TITLE
Seed catkeys

### ISSUE THREAD

**Issue by justinlittman** [sul-dlss/google-books#249]
To avoid pleasing a burden on Symphony looking up catkeys, provide a rake task for loading catkeys from a CSV.

@jgreben has generated such a file: https://drive.google.com/open?id=1kbQQP3WUudtboYATJqdPRxo__L4Ud-ye

**Comment by jcoyne** [comment]
@justinlittman we're going to need to do a lookup from symphony to get the publication location and date of publication anyway.

**Comment by jgreben** [comment]
It would be possible to generate a csv file that includes the publication info if desired.

**Comment by jcoyne** [comment]
@jgreben that would be perfect!

**Comment by jgreben** [comment]
No longer needed. Per @justinlittman
