### ISSUE TITLE
Ensure that FETCH_CATKEY_FAILED is only for 404 responses

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/google-books#259]
The 404 response from dor-services-app indicates that we don't find a catkey for this barcode.  If a 500 or any other exception (timeout, connection reset, etc) is encountered, it should not get  this status.

**Comment by justinlittman** [comment]
Only 404 is caught: https://github.com/sul-dlss/google-books/blob/master/app/services/fetcher_service.rb#L38-L39
