### ISSUE TITLE
Allow for object rights to be different from default APO before accessioning is started

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/google-books#267]
The object rights in an object are set the `rightsMetadata` datastream.  Typically this datastream is pulled from the `defaultObjectRights` datastream of the associated APO and then picked up by the `rights-metadata` robot in accessionWF.  However, you can override these rights for any particular object by creating your own `rightsMetadata.xml` file in the /dor workspace when accessioning (to be picked up by the robot).  

Because Google Books will be using a single collection and a single APO, we will need to have two types of rights being set before accessioning is kicked off.

So we need to be able to pass in the desired rights at the time of registration (or early on in the accessioing process) and make it clear it should be used instead of the default rights in the APO.

See also #303, #1

(2) For books that are out of copyright, which will have a different copyright statement and use and reproduction statement, along with discover and read rights set to world (similar to here: https://argo.stanford.edu/view/druid:bb000kg4251)

This ticket is to make clear the need to have to different types of rights metadata depending on the determination of the object rights as described in #103

**Comment by jcoyne** [comment]
Hey @justinlittman is this resolved by https://github.com/sul-dlss/google-books/blob/c3efd01d0d31166cfd3e87e0593a6b6a5ef1afeb/app/services/fetcher_service.rb#L183 ?

**Comment by peetucket** [comment]
Checked four books, two public domain, two copyrighted.

Public domain: https://argo-stage.stanford.edu/view/druid:sx856xs7428 and https://argo-stage.stanford.edu/view/druid:zq121qd8523

However, these books were accessioned a couple weeks ago and based on further tests below (wher all books are listed as world discoverable), I don't think we have positive confirmation of a public domain book having the correct rights.

They looks fine (world discover and read rights):

```
 <access type="discover">
    <machine>
      <world/>
    </machine>
  </access>
  <access type="read">
    <machine>
      <world/>
    </machine>
  </access>
```

Copyrighted:  https://argo-stage.stanford.edu/view/druid:mz074wc3432 and https://argo-stage.stanford.edu/view/druid:xg355jq5617

This is not correct .. the `type="discover"` block needs to be `<machine><world/></machine>` -- only the `type="read"` block should be  `<machine><none/></machine>`
```
  <access type="discover">
    <machine>
      <none/>
    </machine>
  </access>
  <access type="read">
    <machine>
      <none/>
    </machine>
  </access>
```

Note that objects from a couple weeks ago appear to be wrong (i.e. expect to be copyrighted but found it to be full access).  I assume these are because they were ingested before the ability to assign rights by copyright status was implemented?

 https://argo-stage.stanford.edu/view/druid:qd063kw7046 and https://argo-stage.stanford.edu/view/druid:mk106rb5059 (i.e. world read and discover)

**Comment by peetucket** [comment]
Where is the code that sets the rights?  At a minimum I could have a look at the code. Trying to get a couple examples of barcodes to prioritize for testing from Josh

**Comment by justinlittman** [comment]
https://github.com/sul-dlss/dor-services-app/blob/master/app/services/embargo_service.rb#L4

**Comment by jcoyne** [comment]
So, it looks like we're setting in-copyright things to dark, but they should be citation-only, right?

**Comment by justinlittman** [comment]
Actually, I suspect that the reason the public domain books listed above are correct because they were accessioned before the new cocina deposit was implemented; I suspect that the new cocina deposit does not correctly set rights.

**Comment by justinlittman** [comment]
In particular, I don't think https://github.com/sul-dlss/dor-services-app/blob/master/app/services/registration_service.rb#L131 was implemented for the new cocina deposit.

**Comment by jcoyne** [comment]
Okay, I've added https://github.com/sul-dlss/dor-services-app/issues/700 to address that.
