### ISSUE TITLE
Set correct object rights/embargo for books that are embargoed

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/google-books#268]
As part of determining the copyright status of the book, we additionally need to embargo any books who copyright is set to expire within 5 years.  This means:

1. Knowing how long until the copyright is up (see #103)
2. Setting an embargo datastream that matches what the rights will look like with the object comes out of copyright (see #267)

The actual text for copyright and use and reproduction for each case will be determined in #1

**Comment by andrewjbtw** [comment]
Embargo management documentation is here: https://consul.stanford.edu/display/chimera/Embargo+management+--+the+embargoMetadata+datastream

**Comment by andrewjbtw** [comment]
I believe the parts of this ticket that are actionable now are:

1. Create an embargo datastream when the rights determination indicates it should be embargoed.
2. Set the release date as appropriate for when the item will reach public domain.
