### ISSUE TITLE
Add ability to reset books in an error state

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/google-books#270]
If books end up in an an error state, it seems like it would be helpful to be able to reset them so they can be tried again (for example, after someone at Google resets the ability to download).  Perhaps we need a rake task where we can send in a CSV of barcodes and allow those books to be retried?

**Comment by justinlittman** [comment]
@peetucket We have work partially completed to add this ability to the UI. It just needs to be hooked up.

**Comment by justinlittman** [comment]
<img width="1173" alt="image" src="https://user-images.githubusercontent.com/588335/73995209-ea323d00-4925-11ea-80ee-8c504e9e1d91.png">

**Comment by peetucket** [comment]
Missed that - so this is a dupe of #190?

**Comment by justinlittman** [comment]
Yes.

**Comment by peetucket** [comment]
Dupe of #190
