### ISSUE TITLE
Create API endpoint for libsys to use to update library catalog with status of google books accessioning

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/google-books#278]
In order to support future indexing/faceting in Searchworks and other applications, our Symphony catalog needs to have a few different statuses for each catkey.  Currently each book that was sent to google to be scanned has a status of "DIGISENT", which enables us to know what we sent.  Now that we are getting digitized books back, we'd like to add more info to the symphony record.  

We need an API endpoint that takes Deposit Date range (anything that happened during these days).

It then returns a csv formatted file of barcodes that have completed processing by the google books app (i.e. in the accessioned state) and that book's Copyright state
 - a. Public domain
 - b. In copyright ~~but not embargoed (i.e. out of copyright and past 5 years)~~
~~ In copyright and embargoed (i.e. out of copyright within 5 years)~~

To do this, I think we would need:

- [x] the Google books app database to record catkeys after looking it up from the barcode 
- [ ] the Google books app database to record the copyright status (one of the three possibilities above)
- [ ] a new API endpoint to return catkeys based on the input parameters
- [ ] Remove shibboleth from the API path and have ops handle restriction of machines to this endpoint.

The consumer of the API call would be libsys, and they would be responsible for processing the catkeys and determining which days still need to be requested.

**Comment by jgreben** [comment]
- Specify the mount
- how do we know it was picked up by symphony?
- should this be a database?

**Comment by justinlittman** [comment]
What is the date parameter the date of?

**Comment by peetucket** [comment]
Confirmed from Darsi that this is ok as speced:

```
1.	CSV seems best, any sort of delimited file really
2.	We think date range with a return of barcodes,copyright state will work well for the last stage of the Google Books process.  Getting the copyright state back will handle two potential SearchWorks facets.
 ```

**Comment by aaron-collier** [comment]
Per conversion with @peetucket closing this as the embargo part is no longer useful, but the public_domain part is done. And work down in #357
