### ISSUE TITLE
Ask Google if other image formats (e.g. .TIF) are available for download

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/google-books#28]
- [x] are other image formats available?
- [x] if so, how do we indicate we want other formats?
- [x] how do the file sizes compare?  is there any advantage to requesting a bi-tonal .TIF vs a .JP2 from a file size perspective?
- [x] are other libraries that are working with Google books using other image formats?

**Comment by aaron-collier** [comment]
1 - Yes, we have to request that in our GRIN configuration. So it sounds like while they are available, we'll want to pick the one that we prefer.
2 - Request GRIN configuration
3 - Not a clear answer
4 - Yes. Most libraries use JP2, but there are some that use a mix of JP2/TIFF
