### ISSUE TITLE
Improve date determination algorithm

### ISSUE THREAD

**Issue by justinlittman** [sul-dlss/google-books#302]
From https://github.com/sul-dlss/google-books/issues/103#issuecomment-587243174

1. History of DateType = "t" (publication date and copyright date). If you look at the history section of the MARC 21 documentation<https://www.loc.gov/marc/bibliographic/bd008a.html> for the part of the 008 field that includes the DateType byte, you would see that this type of date situation was not always represented by the code "t", which was added in 1995. Prior to that, records for books used code "c". Here are the relevant statements:

008/06 - Type of date/Publication status
c - Actual date and copyright date (BK, CF, MP, MU, VM) [OBSOLETE]
c - Serial item currently published [REDEFINED, 1995]
t - Publication date and copyright date [NEW, 1995]
Prior to its redefinition, code c had a different definition for books, computer files, maps, music, and visual materials than it did for serials. The difference was eliminated by the definition of a new code t (Publication date and copyright date) which is used in place of the obsolete nonserial code c. The definition of the serial code c was retained.

There are 11735 DIGI-SENT book format records that have DateType = c. We are only looking for a copyright date when DateType = t so we are missing these records. An example is ckey 4073821, which has this publication statement: 260 Boston :|bLittle, Brown,|c1927,c1897. DateType = c, Date1 = 1927, Date2 = 1897. Our pasrsing code is applying this rule when DateType = c:

if Date2 exists and Date2 > Date1, date_used = Date2
if Date1 exists, date_used = Date1

So, in this case it would select 1927, which makes it "in copyright", whereas if it had picked 1897, it would be in the public domain.

2. Date1 and Date2 appear to be "flipped" in their definitions:

@date1 ||= normalize_date(control_field_range('008', 11, 14))
@date2 ||= normalize_date(control_field_range('008', 7, 10))

In HathiTrust's Automated Bibliographic Rights Determination<https://www.hathitrust.org/bib_rights_determination> Date1 is 008:07-10 and Date2 is 008:11-14. The same is true in MARC 21<https://www.loc.gov/marc/bibliographic/bd008a.html>.

**Comment by peetucket** [comment]
See #305 for considerations around copyright and publication date for serials (num 3 and 4 in list above)
