### ISSUE TITLE
Label is set to :auto for google-books items.

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/google-books#316]
See https://sul-dor-test.stanford.edu/fedora/objects/druid:rg151hk5821

**Comment by justinlittman** [comment]
What should it be?

**Comment by jcoyne** [comment]
@justinlittman I believe it should be set to whatever the title gets set to.

**Comment by mjgiarlo** [comment]
Fixed by https://github.com/sul-dlss/dor-services-app/pull/691
