### ISSUE TITLE
Create new status "No catalog record available"

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/google-books#328]
Many of our books are not in the SUL catalog.  It would be nice if these were not lumped in with the "Fetch MARCXML failed" status, which should be reserved for errors that occurred during the fetch,

**Comment by justinlittman** [comment]
@jcoyne It turns out that the "Fetch MARCXML failed" only meant that a record was not found, so I just changed the label to indicate this. The README was already correct.
