### ISSUE TITLE
Deal with symphony being down for 1 hour each night

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/google-books#334]
An early step in the Google Books accessioning pipeline is MARCXML/catakey lookup given a barcode, which hits a libsys API (against symphony).  This API has a known outage for about an hour each night around 1am, which causes many failures (see https://sul-gbooks-stage.stanford.edu/statuses/marcxml-failed).  Assuming there is nothing to be done about this outage, can you pause or retry after some extended period of time (e.g. 1 hour) so that we don't have so many errors?

**Comment by justinlittman** [comment]
This causes deposits to fail during the down time, not https://sul-gbooks-stage.stanford.edu/statuses/marcxml-failed.

**Comment by justinlittman** [comment]
What if we used cron-ed the starting and stopping of sidekiq workers for sdr-api?

**Comment by justinlittman** [comment]
Alternatively, we could look for this specific error in either sdr-api or google-books job and cause to fail, so that is requeued.

**Comment by jcoyne** [comment]
I think the problem is that we're catching the error here: 

https://github.com/sul-dlss/google-books/blob/master/app/jobs/deposit_job.rb#L11

rather than allowing it to raise an error, which would retry the deposit.
