### ISSUE TITLE
Add average conversion time stats

### ISSUE THREAD

**Issue by aaron-collier** [sul-dlss/google-books#339]
Add display of average:

- Time from last_conversion_req_date to last_conversion_completed_date
- Time from last_conversion_req_date and last_deposit_date (note this is just a deposit time, not accession time)

This should provide us with a view into how long, on average, conversion at google is taking, as well as how long from request to deposit, in order to better estimate daily work load.

**Comment by justinlittman** [comment]
Would also be helpful to know this over various timeframes as well (last day, week, month).

**Comment by jcoyne** [comment]
@justinlittman thats #346
