### ISSUE TITLE
shelve/publish/preserve is incorrect for jp2

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/google-books#340]
This was with https://github.com/sul-dlss/sdr-api/pull/144 in staging.
Preserve should be "yes" and shelve & publish should be "no"
```
    <file id="00000001.jp2" size="204016" mimetype="image/jp2" preserve="no" shelve="yes" publish="yes">

```

see https://argo-stage.stanford.edu/view/druid:pg456tt3398

**Comment by jcoyne** [comment]
This looks to me like assemblyWF is overwriting what is already in contentMetadata

**Comment by andrewjbtw** [comment]
That's probably what's happening. Those are the default settings from assembly-objectfile for JP2s.

**Comment by jcoyne** [comment]
I'm going to roll back https://github.com/sul-dlss/sdr-api/pull/144 and that will probably fix this.
