### ISSUE TITLE
Do not HB for FetcherService::FetcherServiceRetriable

### ISSUE THREAD

**Issue by justinlittman** [sul-dlss/google-books#342]
For example, https://app.honeybadger.io/projects/67990/faults/61283332

This is an expected condition and should not be reported to Honeybadger.

**Comment by jermnelson** [comment]
Created PR https://github.com/sul-dlss/shared_configs/pull/1233 that adds `FetcherServiceRetriable` to the Honeybadger exceptions ignore directive.

**Comment by ndushay** [comment]
so is this a matter of updating shared_configs with cap, and restarting passenger with cap?  Cool.  I didn't realize we could even do those configurations.

**Comment by jcoyne** [comment]
@jermnelson I just noticed this ticket calls for `FetcherService::FetcherServiceRetriable` but the shared config change was for `FetcherServiceRetriable`, did you forget the namespace?

**Comment by jermnelson** [comment]
> @jermnelson I just noticed this ticket calls for `FetcherService::FetcherServiceRetriable` but the shared config change was for `FetcherServiceRetriable`, did you forget the namespace?

It wasn't clear to me if the namespace was needed or not from the [documentation](https://docs.honeybadger.io/lib/ruby/getting-started/ignoring-errors.html#ignore-by-class). One of the options is to pass in a regex which could be another alternativve. Happy to add new PR to add the namespace to stage. I'll create the same PR for the Google Book production system.

**Comment by justinlittman** [comment]
We're currently not scheduled to run during the Symphony downtime, so we're not going to see this error. To test, might want to add to schedule.
