### ISSUE TITLE
Move environment specific configuration into shared_configs

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/google-books#352]
There is some configuration currently in the settings.yml file in the app code that will vary by environment and needs to be set in shared_configs settings.yml (by environment).

Obvious examples:

```
sdr_api:
  apo: 'druid:bm476yk3894'
  collection: 'druid:ks963md4872'
```

and be sure sdr-api and dor-services urls and tokens are correct by environment

**Comment by jcoyne** [comment]
I don't think this has to move. Settings will look in the environment variables then the per-environment config and finally the general config. This is working as expected.
