### ISSUE TITLE
Test to see if we can process 1500 books per day

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/google-books#356]
The goal is to determine if we can handle a specific number of books that can be requested, converted, downloaded, and deposited in a day so we can better gauge our throughput for reporting out to stakeholders.  This includes google's throughput, over which we have little control. 

The actual number of try for the test is somewhat arbitrary - chosen to be plausible.  We may need to run this test a few different times with different numbers to get a sense for what the actual number is
~~Adjust the books processed on stage up to a large enough number (e.g. 1000) to find what the top limit is per day.~~

i.e. compute how many books are actually deposited in any given 24 hour period in stage

Potential issue: blocked by potential lack of storage in stage (do some analysis below).
blocked by sul-dlss/technical-metadata-service#82

- [ ] estimate disk space required per book (see accessioning report for some previous work)
- [ ] determine free disk space available in download folder on google books app to see
- [ ] see what the number of books that can be downloaded is on the gb-stage server before we run into space issues there
- [ ] if the number above is > 1500, set the number of books processed in a day to 1500 , and allow it to run for 1 day and see what happens

Caveats:
* stage will have different throughput from prod due to hardware differences, so this is just a guideline
* google's throughput varies day by day

**Comment by justinlittman** [comment]
@peetucket Is the goal of this ticket to know how many books can be requested, converted, downloaded, and deposited in a day OR downloaded and deposited in a day?

In other words, are you trying to test Google and our throughput, or just ours?

**Comment by jcoyne** [comment]
I just downloaded 100 books to stage and it took 7 minutes, so the download step will not be limiting.

**Comment by justinlittman** [comment]
I think we're done with this testing. As predicted, we filled up available storage in multiple places in the stage environment.
