### ISSUE TITLE
Actual and average conversion rate stats look to be wrong in the google-books app

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/google-books#358]
Confirm the computation of these stats is correct.![Screen Shot 2020-02-28 at 2.09.09 PM.png](https://images.zenhubusercontent.com/59b9a35fb0222d5de477a1fb/396b4fb9-7088-4dee-a465-9c23ca1fe21a)

**Comment by aaron-collier** [comment]
This has come up before, I'm pretty sure they are accurate based on the data we have... but now that we have more data I will revisit.

**Comment by aaron-collier** [comment]
I'm also wondering if these are the correct stats (or more specifically, do we want more data?) as this was an early pass and somewhat of a guess at algorithm.

**Comment by aaron-collier** [comment]
Must have hit close accidentally
