### ISSUE TITLE
Get list of barcodes that fall into three categories for reviewing metadata

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/google-books#380]
We need books in these categories accessioned into google stage for reviewing correctness of the objects:

- [x] out of copyright (world discover and read, images shelved)
- [x] in copyright, but out within 5 years (world discover, no read, embargoed to world read, images shelved)
- [x] in copyright, more than 5 years until out (world discover, no read, embargoed to world read, no images shelved)

We thus need some barcodes for books in each of these categories so that we can prioritize them for accessioning in stage.  Can we use the reports already run here to help get barcodes for these categories?

https://github.com/sul-dlss-labs/google_books_pub_dates

**Comment by peetucket** [comment]
This has an example for soon to be out of copyright barcodes: https://github.com/sul-dlss-labs/google_books_pub_dates/blob/master/report/public_domain_swlinks_2020.txt (need to translate ckeys into barcodes by looking at the searchwork records librarian view)

**Comment by jgreben** [comment]
@peetucket is there a particular form that a report should take? For example, should there be a separate file of barcodes for each of the categories, or one file with a label for each of the categories, or something else?

**Comment by peetucket** [comment]
A single list of barcodes in a single file is best (the rake task takes in a csv file), but having the objects identified by category in this ticket will be useful when validating they are correct.  We really only need a handful in each category.

**Comment by jgreben** [comment]
https://github.com/sul-dlss-labs/google_books_pub_dates/blob/master/report/in_copyright_barcodes.txt

https://github.com/sul-dlss-labs/google_books_pub_dates/blob/master/report/out_of_copyright.txt

https://github.com/sul-dlss-labs/google_books_pub_dates/blob/master/report/out_of_copyright_5_years.txt

**Comment by jgreben** [comment]
@peetucket please review and move to closed if the files of barcodes above satisfy the request.
