### ISSUE TITLE
Confirm newly downloaded books have ocr text files

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/google-books#388]
Google has now added plain text ocr files (one per page) to the download package in addition to the HOCR. let's confirm this is true with a newly downloaded book (as of March 5).

**Comment by cncoleman** [comment]
@peetucket I would really like to see an example of this when you have it!

**Comment by andrewjbtw** [comment]
Having two different text file formats will affect how the content search indexing works. We'll need to discuss this.

**Comment by peetucket** [comment]
I suspect its the second OCR file will be plain text, one per page (based on what Google told us in a call last week).  I am assuming we will shelve this file in addition to the other OCR file.  Not sure what the impact is on the access team (I believe the PURL will just offer it is an additional download).

**Comment by cncoleman** [comment]
Is there a significant file size difference between the OCR and the HOCR. I would think it would be significantly smaller.

**Comment by peetucket** [comment]
I suspect it will be much smaller as well, potentially by a factor of 2 - 3.  Once we have some new book examples, we can have a look.

**Comment by andrewjbtw** [comment]
I think if we mark only the HOCR file as "transcription" (as we already do) we should be ok. My concern is just that the text indexer should only look at one of the text-format files, not both.

Content search won't support HOCR until some time in the future, so this wouldn't be an issue now, but could be one when the indexing turns on.

**Comment by justinlittman** [comment]
@andrewjbtw @peetucket I have confirmed that new downloads **DO NOT** have ocr text files.

**Comment by peetucket** [comment]
Interesting - thanks for checking.  I'll ping Google again.

**Comment by peetucket** [comment]
@justinlittman I presumed you confirmed with a new book in the pipeline that we requested a new conversion for first before downloading?  Because this is google's response:

```
Now that the config is in place to add OCR text files to Stanford's download packages, all of the volumes would need to be reconverted, so that the OCR text files appear; the file package would represent whatever config is active at the time of (re)conversion.

Are you seeing something different, though? i.e. you aren't seeing the text file, even after another [new] conversion happens?
```

**Comment by peetucket** [comment]
Google tell us there may be some config issues on their end -- hold for now and we will reconfirm again when they give us the green light.

**Comment by peetucket** [comment]
We've been asked to confirm again.

**Comment by justinlittman** [comment]
Confirmed.

Here's a sample:
[00000024.txt](https://github.com/sul-dlss/google-books/files/4311877/00000024.txt)

**Comment by peetucket** [comment]
great, thanks (though that particular file is empty)

**Comment by peetucket** [comment]
found some examples that are not blank for a recent book https://argo-stage.stanford.edu/view/druid:mg178qn9610
