### ISSUE TITLE
Identify areas in SDR Evolution that make sense to work on during Google Books accessioning

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/google-books#39]

**Comment by jcoyne** [comment]
Evolutions: https://docs.google.com/spreadsheets/d/1EyuszdhVq8aI7ly07zXKK1zLFsOULxNmLay3ZDpDXVM/edit?usp=drive_web&ouid=102156456607618276434

**Comment by justinlittman** [comment]
![SDR Evolution 2019 Updates  ](https://user-images.githubusercontent.com/588335/56654231-976cea80-665d-11e9-95a6-aeaa97920124.jpg)

**Comment by justinlittman** [comment]
For merging provenance and workflow history:
1. Remove provenance metadata step from accessionWF.
2. Remove provenance metadata DS from dor-services.
3. Remove code from Argo for correcting provenance metadata errors.
4. Change SdrIngestService to generate provenance metadata file from info provided by workflow service.
5. Remove references to provenance metadata sprinkled throughout spec code in all repos.

**Comment by justinlittman** [comment]
For swimlaning, should be as easy as adding `-low` queues into the resque-pool configuration, since Resque prioritizes based on the order of the queues. For example:
```
"dor_accessionWF_content-metadata_default,dor_accessionWF_descriptive-metadata_default,dor_accessionWF_content-metadata_low,dor_accessionWF_descriptive-metadata_low": 10
```
and then setting the lane-id when creating the workflow.
