### ISSUE TITLE
Assign books to a collection when accessioning

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/google-books#391]
Google books has an APO and collection. Currently, they are only being assigned to an APO. They should also be getting a collection at deposit.

For stage, this is the collection to use:
https://argo-stage.stanford.edu/view/druid:ks963md4872

**Comment by andrewjbtw** [comment]
Looks like the collection stopped being assigned to google books after 3/17. See for example this book accessioned today: https://argo-stage.stanford.edu/view/druid:pd660tq6196

**Comment by jcoyne** [comment]
@andrewjbtw this is occurring for a totally different cause, so closing this and opening #448
