### ISSUE TITLE
The METS xml and checksum md5 files should not be treated as "page" resources

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/google-books#393]
The METS xml file and the checksum.md5 file downloaded with each book should not be "page" resources. These should be their own objects. 

What we are doing now:
Example: https://argo-stage.stanford.edu/view/druid:dh840tn6627

<img width="620" alt="Screen Shot 2020-03-06 at 11 58 57 AM" src="https://user-images.githubusercontent.com/8975583/76118143-1f23c500-5fa2-11ea-8b5b-6ace0a0db427.png">

What we should be doing:
Example: https://argo.stanford.edu/view/druid:ph649dt5778

<img width="632" alt="Screen Shot 2020-03-06 at 12 03 03 PM" src="https://user-images.githubusercontent.com/8975583/76118339-7a55b780-5fa2-11ea-919b-53076f9d115e.png">

**Comment by andrewjbtw** [comment]
One additional note. In the contentMetadata, these two files should also not be included in the "sequence" numbering for pages. That's probably will be taken care of by making them into their own objects, but it seems worth explicitly noting in the ticket.

**Comment by justinlittman** [comment]
Note from @jcoyne: Resource type (page or object) does not exist in cocina models, so it must be set in dor-services-app. Assembly-file does this by looking to see if the fileset has an image file and sets to page else object.
