### ISSUE TITLE
Do not publish checksum.md5 file

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/google-books#394]
For public domain books, we are marking the checksum.md5 file as publish and preserve. It should only be marked preserve. Publishing it will leave a broken link.

Example: https://argo-stage.stanford.edu/view/druid:dh840tn6627

<img width="632" alt="Screen Shot 2020-03-06 at 12 07 16 PM" src="https://user-images.githubusercontent.com/8975583/76118879-11bb0a80-5fa3-11ea-8ed8-3cf37a1631cf.png">

**Comment by jcoyne** [comment]
This appears to be fixed now:
<img width="412" alt="Screen Shot 2020-03-09 at 9 45 45 AM" src="https://user-images.githubusercontent.com/92044/76225638-cf840a00-61ea-11ea-9466-f654044503e4.png">

See https://argo-stage.stanford.edu/view/druid:wv361qg4556
