### ISSUE TITLE
Set rights for in-copyright books to citation-only

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/google-books#397]
According to our rights decision document https://docs.google.com/document/d/1DdU-MJQOQLIjxQtxC2-sxjpx_P-EM66NtCPkXUvO6G0/edit we will be setting in-copyright books to "citation only". This means that they will have a purl, but files will not be downloadable until they are public domain.

The rights for citation only should be:

discover = world
read = none

Currently, we are assigning in-copyright books the rights that correspond to "dark".

discover = none
read = none

**Important note because documentation about this is confusing**

Normally, "citation-only" means that files are shelved. But this is an exceptional project, where space is not available to shelve everything, so the shelve setting is explicitly being set for each book. That setting should take precedence over what the rights say, so we won't be inadvertently shelving items that shouldn't be shelved.

**Comment by justinlittman** [comment]
Just to be clear: The change I made was to set rights to "citation-only" instead of "dark" for in-copyright books.

Is that the only required changed @andrewjbtw?

**Comment by andrewjbtw** [comment]
Yes, just the rights change.
