### ISSUE TITLE
Include rights statements in embargoMetadata datastream

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/google-books#398]
The public domain rights statement, when we finally have an approved one, should be included in the embargoMetadata datastream. This will become the rights statement when the item goes into the public domain and the embargo is lifted.

Currently, only the rights themselves are in the embargoMetadata datastream, with no statements.

**Comment by jcoyne** [comment]
@andrewjbtw I don't see a place for that to go in the embargoMetadata datastream? https://github.com/sul-dlss/dor-services/blob/master/lib/dor/datastreams/embargo_metadata_ds.rb#L7-L15  Do you know of any other objects that are doing that?

**Comment by andrewjbtw** [comment]
In this case, the only examples I can find are the Google books from last year's analysis, which must have had handcrafted embargoes:
https://argo.stanford.edu/catalog?f%5Bembargo_release_date%5D%5B%5D=all&f%5Bproject_tag_ssim%5D%5B%5D=GoogleBooks

So it may not be necessary, but it does raise the question of the rights statement will say after the embargo is lifted.

**Comment by jcoyne** [comment]
Okay, I think that would work as currently implemented, but it's not a tested or documented feature in the code, so it could easily be overlooked.
