### ISSUE TITLE
Include embargo release date in the rightsMetadata datastream

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/google-books#399]
According to the Consul documentation on embargoMetadata, the embargo release date should be included in the rightsMetadata datastream:
 
https://consul.stanford.edu/display/chimera/Embargo+management+--+the+embargoMetadata+datastream

The documentation gives the following example
```xml
<rightsMetadata>
  <access type="discover">
    <machine>
      <world/>
    </machine>
  </access>
  <access type="read">
    <machine>
      <embargoReleaseDate>2016-06-13T08:00:00Z</embargoReleaseDate>
      <none/>
    </machine>
  </access>
</rightsMetadata>
```

Currently, embargoed items are not including a release date in the rightsMetadata. For example, this item is in the five-year window for release:
https://argo-stage.stanford.edu/view/druid:mv641bs7404

**Comment by jcoyne** [comment]
@andrewjbtw I don't think this has ever been implemented in DOR.  There's nothing in the rightsMetadata datastream that indicates it should be stored there: https://github.com/sul-dlss/dor-services/blob/master/lib/dor/datastreams/rights_metadata_ds.rb#L13-L31

In the past we've found a lot of the consul documentation to not match what was actually implemented.   Do you know of any existent objects that have this field in rightsMetadata?

**Comment by andrewjbtw** [comment]
I believe all of these do, and this is just items set to release in the next 30 days:
https://argo.stanford.edu/catalog?all=true&f%5Bembargo_release_date%5D%5B%5D=days_30

They all appear to be Hydrus or ETD, which are the only apps that currently set embargoMetadata in a user-facing way, as far as I know.

**Comment by andrewjbtw** [comment]
I meant to include the two embargoed books from last year's analysis work cycle on this ticket: https://argo.stanford.edu/catalog?f%5Bembargo_release_date%5D%5B%5D=all&f%5Bproject_tag_ssim%5D%5B%5D=GoogleBooks

Those also have the release date in the rightsMetadata, but presumably Ben had to handcraft these objects to fit the embargo spec.

**Comment by jcoyne** [comment]
I'm a little bit concerned about storing the same data in two different places.  Which one is the canonical one?  What should we do if they don't agree?

**Comment by andrewjbtw** [comment]
That's a valid concern, but it looks like it's what's already implemented and I believe parts of the display depend on having the date in the rightsMetadata. I'm not completely sure, but I think the message at the top of the embed box on the purl comes from rightsMetadata and not embargoMetadata:

https://purl.stanford.edu/hp050gh2646

<img width="502" alt="Screen Shot 2020-03-10 at 10 31 15 AM" src="https://user-images.githubusercontent.com/8975583/76341534-6d92d580-62ba-11ea-8da5-b725b0d81d06.png">

**Comment by jcoyne** [comment]
@andrewjbtw I've confirmed rightsMetadata: https://github.com/sul-dlss/sul-embed/blob/master/app/models/embed/purl.rb#L53
