### ISSUE TITLE
Upload barcodes for researcher use cases to prioritize by download

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/google-books#407]
see #327 for list of barcodes.

**Comment by justinlittman** [comment]
@peetucket Production is ready for prioritization to be loaded.

**Comment by peetucket** [comment]
Ah, sorry about that.  So I guess this is not blocked then?

**Comment by justinlittman** [comment]
Not blocked.

**Comment by jgreben** [comment]
Now blocked by #411

**Comment by justinlittman** [comment]
This is done on production.
