### ISSUE TITLE
Export a list of barcodes in a specific state

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/google-books#409]
From the Google Books app, when you select a state in the left hand column, the user should be able to export a complete list of all of the barcodes in that state and download as a plain text file.

**Comment by justinlittman** [comment]
I'm curious. Why?

**Comment by peetucket** [comment]
Met with Hannah today - she feels this will be useful for the eventual non-engineer project manager tasked with monitoring and remediation.

________________________________

**Comment by justinlittman** [comment]
Which states in particular (as some states may have millions of books)?

**Comment by peetucket** [comment]
My understanding was that the "failed/error" steps would be the ones of most interest since these are the ones requiring some follow up action:

- No MARCXML Record
- Conversion Request Failed
- Conversion Failed
- Download Failed
- MD5 Check Failed
- Deposit Failed

**Comment by justinlittman** [comment]
Great. Those should all be a manageable size.

**Comment by jgreben** [comment]
Peter to find out whether this is just speculative work, or an actual use case.

**Comment by peetucket** [comment]
This is somewhat speculative, but we suspect it will be useful.  Will be helpful to get a sense of scope to make a decision on whether to proceed now (i.e. is it more like 2 hours or 2 days or somewhere in between)?
