### ISSUE TITLE
Add tag for "Project:GoogleBooks"

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/google-books#415]
Google books objects should be given the tag: "Project : GoogleBooks"

**Comment by justinlittman** [comment]
Project tags are in the cocina model as adminstrative > partOfProject.

This will require:
* Adding to cocina model.
* Adding to dor-services-app
 * Adding to openapi.
 * Adding to `object_creator`.
 * Adding to `mapper`.
* Adding to sdr-api.
  * Adding to openapi.
* Adding to `request_generator`.

Project tags are stored in identityMetadata. For example:
```
<?xml version="1.0"?>
<identityMetadata>
  <sourceId source="sul">wprcs_216</sourceId>
  <objectId>druid:fx454qn1277</objectId>
  <objectCreator>DOR</objectCreator>
  <objectLabel>Bay Area Women's Philharmonic, 1st Congregational Church, S. F</objectLabel>
  <objectType>item</objectType>
  <otherId name="catkey">7727411</otherId>
  <otherId name="uuid">6d68d556-bdeb-11e4-b033-0050569b3c3c</otherId>
  <tag>Process : Content Type : File</tag>
  <tag>Project : ARS philharmonic : audio cassette</tag>
  <tag>SMPL : audio : ars : patron request</tag>
  <tag>JIRA : SPECPAT-1651</tag>
  <tag>Registered By : gwillard</tag>
  <release to="Searchworks" what="self" when="2020-01-15T18:59:48Z" who="gwillard">true</release>
</identityMetadata>
```

Note that project tags (prefixed with `Project`) should be treated differently than other tags.
