### ISSUE TITLE
Provide a way for a project manager to stop all downloads/deposits

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/google-books#417]
Once the Google Books app is in production and scaled up, a large flow of books will be running through the system all of the time. In case of an emergency, or in situations when there will be no one available to monitor progress (such as Winter Closure) a project manager will need to be able stop or pause the flow of books to avoid filling up disk space along the download-deposit-accession pipeline.

**When might this be needed?**

- a bug in the deposit mechanism that causes downloads to start filling up the temp space without being cleaned up
- a bug in accessioning that causes deposits to accessions and build up at a particular workflow step, which can mean starting to fill up the /dor workspace
- the project manager is away for an extended time, such as Winter Closure, when no one else will be available to monitor the app

In the past, SDR evolution work has introduced bugs that have stopped accessioning for brief periods of time. This has been manageable because accessioning has not been automated, and we can contact users to ask them to hold off on accessioning. With automated accessioning, we need to modify this approach.

**Why should this be user-facing?**

During the workcycle, developers have been able to turn Google books downloading and/or depositing on and off in response to errors (disk space filling, prescat connection issues, etc.). 

Outside of the workcycle, it is likely to be easier for the Google books project manager, as the primary person responsible for monitoring the app, to be able to halt new Google books downloads/deposits than it will be to make a request for a developer to do the same, especially if the team is on a non-SDR project at the time.

**What could this look like?**

It could be as simple as a button or two for:

- halt downloading new books
- halt depositing new books

Or one button to halt both.

**Comment by peetucket** [comment]
For simplicity in the UI and development, if may make sense to have an option to halt everything only and not individually.  The logic is that if you were to halt deposit but not download, the space that is storing the downloaded books could start to fill up (as you noted above), as it is not designed to hold that many books at any given time.  And if you are going to halt download for some reason, I don't see a compelling reason to not also halt deposit at the same time.
