### ISSUE TITLE
Handle Symphony lookup failures

### ISSUE THREAD

**Issue by justinlittman** [sul-dlss/google-books#426]
There are some MARC records that cause Symphony to 500. This results in:
```
Dor::Services::Client::UnexpectedResponse: Internal Server Error: 500 (Got HTTP Status-Code 500 retrieving 1979429 from Symphony: {"messageList":[{"message":"String index out of range: 74"}]})
```
See for example: https://app.honeybadger.io/projects/67990/faults/61761691

These records must be individually remediated in Symphony.

This is causing the MARCXML retrieval to fail.

Instead of failing MARCXML retrieval, the individual failure should be caught and put in a failed state. This should be distinguished from the MARCXML record not found state, which is unfortunately currently called `FETCH_MARCXML_FAILED`.

**Comment by justinlittman** [comment]
@jgreben Can you confirm that we need to do this, rather than some sort of a fix on the Symphony side?

**Comment by jgreben** [comment]
Yes, confirming. Symphony is not broken. It requires a halt and run as part of it's normal daily operation in order to apply any configuration changes that may have occurred during the day and to load users and do various re-index jobs.

**Comment by justinlittman** [comment]
This isn't about the restart (which we currently handle fine.) This is about Symphony producing 500 given some issue with the record that is being requested.

**Comment by jgreben** [comment]
In that case this would be something that @vitustang might want to take a look into for remediation. The one record that you sent to be had a forward slash character in the Statement of Responsibility field and Web Services choked on that character. There may be other characters in various records. I can also follow up with SirsiDynix to see if these characters are something they can escape in future versions of web services, but that is not a short-term solution.

**Comment by justinlittman** [comment]
OK, then this ticket needs to happen. Adding to ready column.
