### ISSUE TITLE
Create a WER for the decoupling of ETDs from Fedora 3

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/google-books#438]
Examine the current ETD app and come up with a plan and work estimation record for this work for a current workcycle.

- remove ETD related code from common-accessioning and move to ETD app
- decouple ETD from Fedora 
-- use db persistence instead of datastreams
-- build a dashboard for viewing database info (since it will not be visible in fedora datastreams in Argo anymore)
- de-couple ETD from its use of workflow service (etdSubmitWF)
-- this is used to drive business logic internal to ETD app
- make ETDs use SDR deposit API endpoint

NOTE: WER = work estimation record

**Comment by jcoyne** [comment]
See https://github.com/sul-dlss-labs/estimation/pull/19
