### ISSUE TITLE
Ensure there’s a way to see our errors working with GRIN API

### ISSUE THREAD

**Issue by mjgiarlo** [sul-dlss/google-books#54]
This issue is for surfacing errors in our application's interactions with the Google Books API.

Errors that can be encountered include:

- can’t convert
- didn’t scan
- retracted by publisher

Make sure these are surfaced to the user. They should already be recorded in our database.

**Comment by ndushay** [comment]
1.  need to make ticket to put fixture data in this project
2.  JLitt:  "our webapp should report the errors we encounter from GRIN API".
    1.  document that db "status" is about our interactions with google api
