### ISSUE TITLE
Authorize usage of the application by putting it behind Shibboleth authentication

### ISSUE THREAD

**Issue by mjgiarlo** [sul-dlss/google-books#55]
Ask @andrewjbtw which workgroup(s) should be granted access.

**Comment by rsmith11** [comment]
Is `google-books-stage.stanford.edu` an acceptable URL/hostname to use, or is there a particular alias hostname that should be used?  I'll need to request an SSL cert first so wanted to get the hostnames/aliases in order first before shibboleth.

**Comment by rsmith11** [comment]
Also, should the entire site be behind Shibboleth, or is there a specific path that needs shibboleth?

**Comment by mjgiarlo** [comment]
@rsmith11 Yes, that hostname is perfect and we want the whole site behind shib. Thanks!

**Comment by rsmith11** [comment]
Are there particular workgroups that should be allowed?

**Comment by mjgiarlo** [comment]
:point_up: @peetucket what do you think?

**Comment by peetucket** [comment]
Is there is a workgroup that is as wide as "SUL staff"?  It would be nice to not be all of Stanford if possible, but not sure we can be as restrictive as DLSS only.

**Comment by rsmith11** [comment]
Basic Shib setup on -stage with any SUNet allowed in until we get workgroups figured out.

**Comment by rsmith11** [comment]
Requested workgroups access for both stage and prod entityIDs.

**Comment by rsmith11** [comment]
Shibboleth setup to use sul:staff workgroup on both stage and prod.
