### ISSUE TITLE
Ensure we have access to all books that Stanford has sent to Google

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/google-books#7]
pre-req / depends on #16 

We should have the ability to download any books that Stanford owns and has sent for digitizing.  We should be able to get a report of barcodes of these books from library systems or metadata.  However, if Google had already scanned a book we sent them (since they got it from another library) they won't scan our version.  However, we still need to be able to download that book (since we own a physical copy).  Not sure what happens if we request by our barcode... do we get a book or not?

**Comment by aaron-collier** [comment]
Closing as this is not completely possible. There are books with a "not allowed to download" state that we are unable to convert and download.
