### ISSUE TITLE
Download and decrypt a book that has been processed by google

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/google-books#78]
In the current pipeline, after we have requested and confirmed that a book has been processed by Google, we should do the next step (which id download and decrypt it).

**Comment by justinlittman** [comment]
For setting a max threshold of 2: https://github.com/sul-dlss/shared_configs/pull/1180

**Comment by justinlittman** [comment]
For setting grin passphrase: https://github.com/sul-dlss/shared_configs/pull/1181
