### ISSUE TITLE
Decide on if Google Books should be a collection, and if so, create the collection for the Google Books 

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/google-books#86]
Do we need a collection?  Should we use a single collection

**Comment by mjgiarlo** [comment]
@peetucket Hi! Is this in progress or should we leave it in ready?

**Comment by peetucket** [comment]
I can sort through this with Andrew this week - let's leave here for now.

**Comment by andrewjbtw** [comment]
Question from 2020-01-15:

Should Google Books even be in its own collection?

**Comment by jcoyne** [comment]
We need to put the books in a collection as this is a requirement of the registration process.  It can be an existing collection or a new collection. This can be a single collection for all google books or we can pick a specific collection for each book depending on a rubric to be provided by a stakeholder.

**Comment by andrewjbtw** [comment]
I just tested this, and it turns out that it is possible to register an item without a collection:
https://argo.stanford.edu/view/druid:jh181qt6297

**Comment by peetucket** [comment]
I emailed Nicole, Arcadia, and Jessica seeking feedback and input.

**Comment by jcoyne** [comment]
If you don’t use a collection, is the release process more or less difficult?

**Comment by peetucket** [comment]
I don't think it matters.  Collection release just iterates through all of the items, and releases them one by one (via the releaseWF workflow per item I think).  I think doing an item by item release is less likely to expose issues with releasing a giant collection all at once (and follows our model of a slow accession of books anyway).
