### ISSUE TITLE
Create the google-books prod environment

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/google-books#87]
This may require writing a ticket to https://github.com/sul-dlss/operations-tasks and creating a branch of shared-configs.

**Comment by mjgiarlo** [comment]
@jcoyne also create shared_configs? Or separate issue?

**Comment by jcoyne** [comment]
@mjgiarlo I've added that to the description.

**Comment by jermnelson** [comment]
Operations ticket [#2113](https://github.com/sul-dlss/operations-tasks/issues/2113)

Shared configs branch: https://github.com/sul-dlss/shared_configs/tree/google-books-prod

Still needs puppet to be set-up.
